// get Accounts
GET http://localhost:8080/accounts
Content-Type: application/json
username: admin
password: heroes3

###

GET http://localhost:8080/accounts/names
Content-Type: application/json
username: admin
password: heroes3

###

DELETE http://localhost:8080/accounts/TEST
Content-Type: application/json
username: admin
password: heroes3

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "username": "admin",
  "password": "heroes3"
}

###

GET http://localhost:8080/auth
Content-Type: application/json
username: admin
password: heroes3

###

POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "test",
  "password": "heroes3",
  "decks": []
}

###

// PRODUCTION


GET https://duelofwarlords.ru/accounts
Content-Type: application/json
username: admin
password: heroes3

###

// get Account
GET  https://duelofwarlords.ru/accounts/Vik
Content-Type: application/json
username: admin
password: heroes3

###


GET  https://duelofwarlords.ru/auth
Content-Type: application/json
username: Vik
password: supergame

###