// get Accounts
GET http://localhost:8080/accounts
Content-Type: application/json
username: admin
password: heroes3

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "username": "admin",
  "password": "heroes3"
}

###

GET http://localhost:8080/auth
Content-Type: application/json
username: admin
password: heroes3

###

POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "test",
  "password": "heroes3",
  "decks": []
}

###