/* eslint-disable max-len */
import _ from 'lodash';
import Swift from '../../assets/airSpells/Swift.png';
import ThunderBlast from '../../assets/airSpells/ThunderBlast.png';
import LightningStrike from '../../assets/airSpells/LightningStrike.png';
import Dodge from '../../assets/airSpells/Dodge.png';
import LightningPower from '../../assets/airSpells/LightningPower.png';
import ThunderWeapon from '../../assets/airSpells/ThunderWeapon.png';
import AirFlows from '../../assets/airSpells/AirFlows.png';

export default {
  Swiftness: {
    name: 'Swiftness',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: ['SWIFT'],
    description: 'Swiftness',
    school: 'Air',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior'],
      type: 'good',
      name: 'swift',
      aimStatus: 'field',
    }],
    img: Swift,
    status: 'hand',
    disabled: false,
  },
  ThunderBlast: {
    name: 'Thunder Blast',
    type: 'spell',
    subtype: 'instant',
    cost: 4,
    currentC: 4,
    featInfo: [],
    description: 'ThunderBlast',
    school: 'Air',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 4, depend: 'postponed', dependValue: 4, aimStatus: 'field', school: 'air',
    },
    {
      spell: true, attach: false, type: 'all', aim: ['adjacent', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', aimStatus: 'field',
    }],
    img: ThunderBlast,
    status: 'hand',
    disabled: false,
  },
  LightningStrike: {
    name: 'Lightning Strike',
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'LightningStrike',
    school: 'Air',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 4, aimStatus: 'field', depend: 'lastPlayedIsSpell', dependValue: 1, school: 'air',
    },
    ],
    img: LightningStrike,
    status: 'hand',
    disabled: false,
  },
  Dodge: {
    name: 'Dodge',
    type: 'spell',
    subtype: 'reaction',
    cost: 1,
    currentC: 1,
    featInfo: ['REACTION'],
    description: 'Dodge',
    school: 'Air',
    id: _.uniqueId(),
    place: 'bigSpell',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    features: [{
      spell: true, attach: ['field', 'hero'], aim: ['warrior', 'fighter', 'shooter', 'flyer', 'spell'], type: 'good', name: 'protection', value: { type: 'number', val: 100 }, charges: 1, aimStatus: 'field', cost: 1, subtype: 'reaction',
    }],
    img: Dodge,
    status: 'hand',
    disabled: false,
  },
  LightningPower: {
    name: 'Lightning Power',
    type: 'spell',
    subtype: 'permanent',
    cost: 3,
    currentC: 3,
    featInfo: ['SWIFT', 'PIERCING'],
    description: 'LightningPower',
    school: 'Air',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior'],
      type: 'good',
      name: 'swift',
      aimStatus: 'field',
    }, {
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aimStatus: 'field',
      name: 'attack',
      condition: 'onattack',
      type: 'bad',
      aim: ['otherWarInRow', 'warrior', 'flyer', 'shooter', 'fighter'],
      value: 2,
      apply: 'attacked',
      school: 'air',
    }],
    img: LightningPower,
    status: 'hand',
    disabled: false,
  },
  ThunderWeapon: {
    name: 'Thunder Weapon',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: ['SHOCKWAVE'],
    description: 'ThunderWeapon',
    school: 'Air',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      description: 'shockWaveCast',
      type: 'good',
      value: {
        img: ThunderWeapon,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        description: 'ShockWaveCast',
        school: 'Air',
        place: '',
        featInfo: [],
        features: [{
          attach: false, aim: ['emptyRowField', 'adjacent', 'warrior', 'flyer', 'shooter', 'fighter'], type: 'bad', name: 'attack', value: 2, aimStatus: 'field', school: 'air',
        }],
        status: 'hand',
      },
      condition: 'insteadatk',
      cost: 0,
    }],
    img: ThunderWeapon,
    status: 'hand',
    disabled: false,
  },
  // ArrowsRain: {
  //   name: 'Arrows Rain',
  //   id: _.uniqueId(),
  //   type: 'spell',
  //   subtype: 'temporary',
  //   cost: 1,
  //   currentC: 1,
  //   featInfo: [],
  //   description: 'ArrowsRain',
  //   school: 'Air',
  //   place: 'bigSpell',
  //   features: [{
  //     spell: true, attach: ['field', 'warrior'], aim: ['warrior', 'shooter'], type: 'good', name: 'massAttack', aimStatus: 'field',
  //   }],
  //   img: ArrowsRain,
  //   status: 'hand',
  // },
  AirFlows: {
    name: 'Air flows',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: ['SWIFT'],
    description: 'AirFlows',
    school: 'Air',
    place: 'midSpell',
    features: [{
      spell: true, attach: ['row', 'cards', 'flyer', 'shooter', 'fighter'], type: 'good', aim: ['field', 'warrior', 'flyer', 'shooter', 'fighter'], charges: null, name: 'swift', aimStatus: 'field',
    }],
    img: AirFlows,
    status: 'hand',
  },
};
