import _ from 'lodash';
import FireArrow from '../../assets/fireSpells/FireArrow.png';
import MeteorShower from '../../assets/fireSpells/MeteorShower.png';
import FireBall from '../../assets/fireSpells/FireBall.png';
import ExplosiveTrap from '../../assets/fireSpells/ExplosiveTrap.png';
import Rage from '../../assets/fireSpells/Rage.png';
import PowerOfFire from '../../assets/fireSpells/PowerOfFire.png';
import FireSplash from '../../assets/fireSpells/FireSplash.png';
import FireShield from '../../assets/fireSpells/FireShield.png';
import FireBlast from '../../assets/fireSpells/FireBlast.png';
import Ignition from '../../assets/fireSpells/Ignition.png';
import Blindness from '../../assets/fireSpells/Blindness.png';

export default {
  FireArrow: {
    name: 'Fire Arrow',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'FireArrow',
    school: 'Fire',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true,
      attach: false,
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'bad',
      name: 'attack',
      value: 2,
      aimStatus: 'field',
    },
    ],
    img: FireArrow,
    status: 'hand',
    disabled: false,
  },
  MeteorShower: {
    name: 'Meteor Shower',
    type: 'spell',
    subtype: 'instant',
    cost: 4,
    currentC: 4,
    featInfo: [],
    description: 'MeteorShower',
    school: 'Fire',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true, attach: false, type: 'all', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 3, aimStatus: 'field',
    },
    {
      spelll: true, attach: false, type: 'bad', aim: ['randomNextRow', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 3, aimStatus: 'field',
    },
    ],
    img: MeteorShower,
    status: 'hand',
    disabled: false,
  },
  FireBall: {
    name: 'Fire Ball',
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'FireBall',
    school: 'Fire',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true,
      attach: false,
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'bad',
      name: 'attack',
      value: 3,
      aimStatus: 'field',
      depend: 'lastPlayedIsSpell',
      dependValue: 1,
    },
    ],
    img: FireBall,
    status: 'hand',
    disabled: false,
  },
  PowerOfFire: {
    name: 'Power of Fire',
    type: 'spell',
    subtype: 'turn',
    cost: 6,
    currentC: 6,
    featInfo: [],
    description: 'PowerOfFire',
    school: 'Fire',
    id: _.uniqueId(),
    place: 'bigSpell',
    features: [{
      spell: true,
      attach: ['field', 'warrior', 'flyer', 'shooter', 'fighter'],
      type: 'good',
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      name: 'power',
      value: 2,
      aimStatus: 'field',
    }],
    img: PowerOfFire,
    status: 'hand',
    disabled: false,
  },
  Rage: {
    name: 'Rage',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'Rage',
    school: 'Fire',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      type: 'good',
      name: 'power',
      value: 1,
      aimStatus: 'field',
    }],
    img: Rage,
    status: 'hand',
    disabled: false,
  },
  ExplosiveTrap: {
    name: 'Explosive trap',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'reaction',
    cost: 2,
    currentC: 2,
    featInfo: ['REACTION'],
    description: 'ExplosiveTrap',
    school: 'Fire',
    place: 'bigSpell',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    features: [
      {
        spell: true, attach: ['field', 'warrior'], type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'moveRandomNextRowCell', charges: 1, condition: 'onplay', aimStatus: 'field', cost: 0, subtype: 'reaction',
      },
      {
        spell: true, attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 4, condition: 'onplay', type: 'bad', aimStatus: 'field', cost: 2, subtype: 'reaction',
      },
      {
        spell: true, attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'moveRandomNextRowCell', condition: 'onmove', type: 'bad', aimStatus: 'field', cost: 0, subtype: 'reaction',
      },
      {
        spell: true, attach: ['field', 'warrior'], type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 4, charges: 1, condition: 'onmove', aimStatus: 'field', cost: 2, subtype: 'reaction',
      }],
    img: ExplosiveTrap,
    status: 'hand',
  },
  FireSplash: {
    name: 'Fire Splash',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'FireSplash',
    school: 'Fire',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 1, depend: 'postponed', dependValue: 4, aimStatus: 'field',
    },
    {
      spell: true, attach: false, type: 'all', aim: ['adjacent', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 1, aimStatus: 'field',
    }],
    img: FireSplash,
    status: 'hand',
    disabled: false,
  },
  FireBlast: {
    name: 'Fire Blast',
    type: 'spell',
    subtype: 'instant',
    cost: 6,
    currentC: 6,
    featInfo: [],
    description: 'FireBlast',
    school: 'Fire',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 4, aimStatus: 'field',
    },
    {
      spell: true, attach: false, type: 'all', aim: ['adjacent', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 4, aimStatus: 'field',
    }],
    img: FireBlast,
    status: 'hand',
    disabled: false,
  },
  FireShield: {
    name: 'Fire Shield',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'FireShield',
    school: 'Fire',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'good',
      name: 'retaliatestrike',
      value: 0,
      depend: 'attackerPower',
      aimStatus: 'field',
    },
    ],
    img: FireShield,
    status: 'hand',
    disabled: false,
  },
  Ignition: {
    name: 'Attack Aura',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: ['LASTCAST'],
    description: 'Ignition',
    school: 'Fire',
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        spell: true, attach: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: '', value: 0, aimStatus: 'field',
      },
      {
        spell: true, attach: false, type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'attack', value: 2, aimStatus: 'field',
      },
      {
        spell: true, attach: false, type: 'bad', aim: ['warInCell', 'flyer', 'shooter', 'fighter', 'spell'], name: 'attack', condition: 'lastcall', value: 3, aimStatus: 'field',
      },
    ],
    img: Ignition,
    status: 'hand',
    disabled: false,
  },
  Blindness: {
    name: 'Blindness',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Blindness',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    school: 'Fire',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'bad',
      name: 'unarmed',
      aimStatus: 'field',
    },
    {
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'bad',
      name: 'power',
      value: -50,
      aimStatus: 'field',
    },
    // {
    //   spell: true,
    //   attach: ['warrior', 'flyer', 'shooter', 'fighter'],
    //   aim: ['warrior', 'flyer', 'shooter', 'fighter'],
    //   type: 'bad',
    //   name: 'immobile',
    //   aimStatus: 'field',
    // },
    {
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'bad',
      name: 'protection',
      value: { type: 'number', val: 0 },
      charges: 1,
      hide: 'true',
      aimStatus: 'field',
    },
    ],
    img: Blindness,
    status: 'hand',
    disabled: false,
  },
};
