import _ from 'lodash';
import Сonciliation from '../../assets/lightSpells/Сonciliation.png';
import Bless from '../../assets/lightSpells/Bless.png';
import Enlightenment from '../../assets/lightSpells/Enlightenment.png';
import HealingLight from '../../assets/lightSpells/HealingLight.png';
import HeavenProtection from '../../assets/lightSpells/HeavenProtection.png';
import HeavenShock from '../../assets/lightSpells/HeavenShock.png';
import HolyLand from '../../assets/lightSpells/HolyLand.png';
import AttackAura from '../../assets/lightSpells/AttackAura.png';
import LastChance from '../../assets/lightSpells/LastChance.png';
import LightShield from '../../assets/lightSpells/LightShield.png';
import Resurrection from '../../assets/lightSpells/Resurrection.png';
import SaintWord from '../../assets/lightSpells/SaintWord.png';
import GuardianAngel from '../../assets/lightSpells/GuardianAngel.png';
// import RetributionSword from '../../assets/castleCards/RetributionSword.png';

export default {
  Resurrection: {
    name: 'Resurrection',
    type: 'spell',
    subtype: 'instant',
    cost: 4,
    currentC: 4,
    featInfo: [],
    description: 'Resurrection',
    school: 'Light',
    id: _.uniqueId(),
    place: 'graveyard',
    features: [{
      spell: true,
      attach: ['grave'],
      type: 'good',
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      name: 'ressurect',
      cost: 4,
      resCost: 0,
      aimStatus: 'graveyard',
    }],
    img: Resurrection,
    status: 'hand',
    disabled: false,
  },
  AttackAura: {
    name: 'Attack Aura',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: ['LASTCAST'],
    description: 'AttackAura',
    school: 'Light',
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        spell: true, attach: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'good', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: '', value: 0, aimStatus: 'field',
      },
      {
        spell: true, attach: false, type: 'good', aim: ['closestEnemyInRow', 'warrior', 'spell', 'flyer', 'shooter', 'fighter'], name: 'attack', condition: 'lastcall', value: 2, aimStatus: 'field',
      },
      {
        spell: true, attach: false, type: 'good', aim: ['closestEnemyInRow', 'warrior', 'flyer', 'shooter', 'fighter'], name: 'attack', value: 2, aimStatus: 'field',
      },
    ],
    img: AttackAura,
    status: 'hand',
    disabled: false,
  },
  HealingLight: {
    name: 'Healing Light',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'HealingLight',
    school: 'Light',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true, attach: false, aim: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'good', name: 'heal', depend: 'postponed', value: 3, dependValue: 4, aimStatus: 'field',
    }],
    img: HealingLight,
    status: 'hand',
    disabled: false,
  },
  Enlightenment: {
    name: 'Enlightenment',
    type: 'spell',
    subtype: 'turn',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'Enlightenment',
    school: 'Light',
    id: _.uniqueId(),
    place: 'bigSpell',
    features: [{
      spell: true,
      attach: ['field', 'warrior', 'flyer', 'shooter', 'fighter'],
      type: 'good',
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      name: 'power',
      value: 1,
      aimStatus: 'field',
    }],
    img: Enlightenment,
    status: 'hand',
    disabled: false,
  },
  HeavenProtection: {
    name: 'Heaven Protection',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'HeavenProtection',
    school: 'Light',
    id: _.uniqueId(),
    showCharges: false,
    charges: 1,
    curCharges: 1,
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 100 },
      charges: 1,
      aimStatus: 'field',
    }],
    img: HeavenProtection,
    status: 'hand',
    disabled: false,
  },
  Bless: {
    name: 'Bless',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Bless',
    school: 'Light',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      type: 'good',
      name: 'power',
      value: 1,
      aimStatus: 'field',
    }],
    img: Bless,
    status: 'hand',
    disabled: false,
  },
  HolyLand: {
    name: 'Holy Land',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'HolyLand',
    school: 'Light',
    id: _.uniqueId(),
    place: 'midSpell',
    features: [
      {
        spell: true, attach: false, type: 'bad', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], value: 1, name: 'attack', aimStatus: 'field',
      },
      {
        spell: true,
        attach: ['row', 'warrior', 'flyer', 'shooter', 'fighter'],
        type: 'bad',
        aim: ['warrior', 'fighter', 'shooter', 'flyer'],
        name: 'attack',
        condition: 'onmove',
        value: 2,
        aimStatus: 'field',
      },
      {
        spell: true,
        attach: ['row', 'warrior'],
        type: 'bad',
        aim: ['warrior', 'fighter', 'shooter', 'flyer'],
        name: 'attack',
        condition: 'onplay',
        value: 2,
        aimStatus: 'field',
      }],
    img: HolyLand,
    status: 'hand',
    disabled: false,
  },
  HeavenShock: {
    name: 'Heaven Shock',
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'HeavenShock',
    school: 'Light',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true,
      attach: false,
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'bad',
      name: 'attack',
      value: 2,
      aimStatus: 'field',
    },
    {
      spell: true, attach: false, aim: ['hero', 'warrior'], type: 'good', name: 'heroHeal', value: 2,
    },
    ],
    img: HeavenShock,
    status: 'hand',
    disabled: false,
  },
  SaintWord: {
    name: 'Saint Word',
    type: 'spell',
    subtype: 'instant',
    cost: 4,
    currentC: 4,
    featInfo: [],
    description: 'SaintWord',
    school: 'Light',
    id: _.uniqueId(),
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 2, depend: 'postponed', dependValue: 3, aimStatus: 'field',
    },
    {
      attach: false, type: 'bad', aim: ['randomNextRow', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 2, aimStatus: 'field',
    },
    ],
    img: SaintWord,
    status: 'hand',
    disabled: false,
  },
  LightShield: {
    name: 'LightShield',
    type: 'spell',
    subtype: 'permanent',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'LightShield',
    school: 'Light',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'good',
      name: 'health',
      value: 2,
      aimStatus: 'field',
    },
    {
      spell: true,
      attach: false,
      aim: ['warrior'],
      type: 'good',
      name: 'health',
      value: 2,
      aimStatus: 'field',
    }],
    img: LightShield,
    status: 'hand',
    disabled: false,
  },
  LastChance: {
    name: 'Last Chance',
    type: 'spell',
    subtype: 'reaction',
    cost: 1,
    currentC: 1,
    featInfo: ['REACTION'],
    description: 'LastChance',
    school: 'Light',
    id: _.uniqueId(),
    place: 'bigSpell',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    features: [{
      spell: true,
      attach: ['field', 'warrior'],
      type: 'good',
      aim: ['warrior', 'fighter', 'shooter', 'flyer'],
      name: 'protection',
      condition: 'canDie',
      value: { type: 'immortal', val: 0 },
      charges: 1,
      aimStatus: 'field',
      cost: 1,
      subtype: 'reaction',
    }],
    img: LastChance,
    status: 'hand',
    disabled: false,
  },
  GuardianAngel: {
    name: 'Guardian Angel',
    type: 'spell',
    subtype: 'reaction',
    cost: 2,
    currentC: 2,
    featInfo: ['REACTION'],
    description: 'GuardianAngel',
    school: 'Light',
    id: _.uniqueId(),
    place: 'bigSpell',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    features: [{
      spell: true,
      attach: ['field', 'hero'],
      aim: ['field', 'warrior', 'fighter', 'shooter', 'flyer', 'spell', 'hero'],
      type: 'good',
      condition: 'gotAttacked',
      name: 'heal',
      value: 2,
      cost: 2,
      aimStatus: 'field',
      subtype: 'reaction',
    },
    {
      spell: true, attach: ['field', 'hero'], type: 'good', name: 'protection', aim: ['warrior', 'flyer', 'shooter', 'fighter', 'spell'], value: { type: 'number', val: 2 }, aimStatus: 'field', charges: 1, hide: true,
    },
    ],
    img: GuardianAngel,
    status: 'hand',
    disabled: false,
  },
  Conciliation: {
    name: 'Conciliation',
    type: 'spell',
    subtype: 'temporary',
    cost: 5,
    currentC: 5,
    featInfo: [],
    description: 'Conciliation',
    school: 'Light',
    id: _.uniqueId(),
    place: 'bigSpell',
    features: [{
      spell: true, attach: ['field', 'warrior'], type: 'good', name: 'protection', aim: ['warrior', 'spell', 'fighter', 'shooter', 'flyer'], value: { type: 'number', val: 100 }, aimStatus: 'field',
    }],
    img: Сonciliation,
    status: 'hand',
    disabled: false,
  },
};
