import _ from 'lodash';
import ArcaneArmor from '../../assets/academiaCards/ArcaneArmor.png';
import CursedShackle from '../../assets/academiaCards/CursedShackle.png';
import InvisibilityCloak from '../../assets/academiaCards/InvisibilityCloak.png';
import SoulDrain from '../../assets/academiaCards/SoulDrain.png';
import Teleport from '../../assets/academiaCards/Teleport.png';
import TownPortal from '../../assets/academiaCards/TownPortal.png';
import Transformation from '../../assets/academiaCards/Transformation.png';

export default {
  ArcaneArmor: {
    name: 'Arcane armor',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: ['REACTION'],
    description: 'ArcaneArmor',
    school: 'Shadow',
    place: 'postponed',
    features: [{
      attach: ['field', 'warrior', 'hero'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'good', name: 'protection', value: { type: 'number', val: 100 }, charges: 1, condition: 'minPower', conditionValue: 3, aimStatus: 'field',
    }],
    img: ArcaneArmor,
    status: 'hand',
  },
  CursedChackle: {
    name: 'Cursed chackle',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'CursedChackle',
    school: 'Shadow',
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior', 'flyer', 'shooter', 'fighter'],
        type: 'bad',
        condition: 'onattack',
        name: 'selfHeroAttack',
        value: 'power',
        apply: 'attacker',
        aimStatus: 'field',
      },
    ],
    img: CursedShackle,
    status: 'hand',
  },
  InvisibilityCloak: {
    name: 'Invisibility cloak',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: ['INVISIBILITY', 'MAGICSHIELD'],
    description: 'InvisibilityCloak',
    school: 'Shadow',
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior', 'flyer', 'shooter', 'fighter'],
        type: 'good',
        name: 'invisible',
        aimStatus: 'field',
      },
      {
        attach: ['warrior'], type: 'good', name: 'protection', value: { type: 'percent', val: 0.5 }, aim: ['spell'], aimStatus: 'field',
      },
    ],
    img: InvisibilityCloak,
    status: 'hand',
  },
  SoulDrain: {
    name: 'Soul drain',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 5,
    currentC: 5,
    featInfo: [],
    description: 'SoulDrain',
    school: 'Shadow',
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'attack', value: 200, aim: ['warrior', 'flyer', 'shooter', 'fighter'], aimStatus: 'field',
    }],
    img: SoulDrain,
    status: 'hand',
  },
  Teleport: {
    name: 'Teleport',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'Teleport',
    school: 'Shadow',
    place: '',
    features: [{
      attach: ['warrior'], type: 'good', aim: ['warrior', 'flyer', 'shooter', 'fighter'], charges: 1, name: 'moving', aimStatus: 'field', immediate: true,
    }],
    img: Teleport,
    status: 'hand',
  },
  TownPortal: {
    name: 'Town portal',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'TownPortal',
    school: 'Shadow',
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'return', aim: ['warrior', 'flyer', 'shooter', 'fighter'], aimStatus: 'field',
    }],
    img: TownPortal,
    status: 'hand',
  },
  Transformation: {
    name: 'Transformation',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'Transformation',
    school: 'Shadow',
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'stun', aim: 'warrior', aimStatus: 'field',
    }, {
      attach: ['warrior'], aim: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'bad', name: 'moveNextRow', aimStatus: 'field', charges: 1, immediate: true,
    }],
    img: Transformation,
    status: 'hand',
  },
};
