/* eslint-disable max-len */
import _ from 'lodash';
import ArcaneArmor from '@assets/shadowSpells/ArcaneArmor.png';
import CursedShackle from '@assets/shadowSpells/CursedShackle.png';
import SoulDrain from '@assets/shadowSpells/SoulDrain.png';
import Teleport from '@assets/shadowSpells/Teleport.png';
import TownPortal from '@assets/shadowSpells/TownPortal.png';
import Transformation from '@assets/shadowSpells/Transformation.png';
import MagicMist from '@assets/shadowSpells/MagicMist.png';
import MassPowerDrain from '@assets/shadowSpells/MassPowerDrain.png';
import SinisterFog from '@assets/shadowSpells/SinisterFog.png';

export default {
  ArcaneArmor: {
    name: 'Arcane armor',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'reaction',
    cost: 1,
    currentC: 1,
    featInfo: ['REACTION'],
    description: 'ArcaneArmor',
    school: 'Shadow',
    place: 'bigSpell',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    features: [{
      spell: true, attach: ['field', 'warrior', 'hero'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'good', name: 'protection', value: { type: 'number', val: 100 }, charges: 1, condition: 'minPower', conditionValue: 3, aimStatus: 'field', cost: 1, subtype: 'reaction',
    }],
    img: ArcaneArmor,
    status: 'hand',
  },
  CursedChackle: {
    name: 'Cursed chackle',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'CursedChackle',
    school: 'Shadow',
    place: 'warrior',
    features: [
      {
        spell: true,
        attach: ['warrior', 'flyer', 'shooter', 'fighter'],
        aim: ['warrior', 'flyer', 'shooter', 'fighter'],
        type: 'bad',
        condition: 'onattack',
        name: 'selfHeroAttack',
        value: 'power',
        apply: 'attacker',
        aimStatus: 'field',
      },
    ],
    img: CursedShackle,
    status: 'hand',
  },
  SoulDrain: {
    name: 'Soul drain',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 5,
    currentC: 5,
    featInfo: [],
    description: 'SoulDrain',
    school: 'Shadow',
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', name: 'attack', value: 200, aim: ['warrior', 'flyer', 'shooter', 'fighter'], aimStatus: 'field', school: 'arcane',
    }],
    img: SoulDrain,
    status: 'hand',
  },
  MassPowerDrain: {
    name: 'Mass power drain',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 6,
    currentC: 6,
    featInfo: [],
    description: 'MassPowerDrain',
    school: 'Shadow',
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', name: 'attack', value: 2, aim: ['field', 'warrior', 'flyer', 'shooter', 'fighter'], aimStatus: 'field', school: 'arcane',
    },
    {
      spell: true, attach: false, type: 'good', name: 'heal', value: 2, aim: ['field', 'warrior', 'flyer', 'shooter', 'fighter'], aimStatus: 'field', school: 'light',
    }],
    img: MassPowerDrain,
    status: 'hand',
  },
  Teleport: {
    name: 'Teleport',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'Teleport',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    school: 'Shadow',
    place: '',
    features: [{
      spell: true, attach: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'good', aim: ['warrior', 'flyer', 'shooter', 'fighter'], charges: 1, name: 'moving', aimStatus: 'field', immediate: true,
    }],
    img: Teleport,
    status: 'hand',
  },
  TownPortal: {
    name: 'Town portal',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'TownPortal',
    school: 'Shadow',
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', name: 'return', aim: ['warrior', 'flyer', 'shooter', 'fighter'], aimStatus: 'field',
    }],
    img: TownPortal,
    status: 'hand',
  },
  Transformation: {
    name: 'Transformation',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: ['STUN'],
    description: 'Transformation',
    school: 'Shadow',
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', name: 'stun', aim: ['warrior', 'fighter', 'shooter', 'flyer'], aimStatus: 'field',
    },
    {
      spell: true, attach: ['warrior'], type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'moveAdjasent', charges: 1, immediate: true, aimStatus: 'field',
    },
    //  {
    //   spell: true, attach: ['warrior'], aim: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'bad', name: 'moveNextRow', aimStatus: 'field', charges: 1, immediate: true,
    // }
    ],
    img: Transformation,
    status: 'hand',
  },
  MagicMist: {
    name: 'Magic Mist',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: ['INVISIBILITY'],
    description: 'MagicMist',
    school: 'Shadow',
    place: 'warrior',
    features: [
      {
        spell: true,
        attach: ['warrior', 'flyer', 'shooter', 'fighter'],
        aim: ['warrior', 'flyer', 'shooter', 'fighter'],
        type: 'all',
        name: 'invisible',
        aimStatus: 'field',
      },
      {
        spell: true,
        attach: ['warrior', 'flyer', 'shooter', 'fighter'],
        aim: ['warrior', 'flyer', 'shooter', 'fighter'],
        type: 'all',
        name: 'ignoreRetalation',
        aimStatus: 'field',
      },
    ],
    img: MagicMist,
    status: 'hand',
  },
  SinisterFog: {
    name: 'Sinister Fog',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'SinisterFog',
    school: 'Shadow',
    place: 'bigSpell',
    features: [{
      spell: true, attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'bad', name: 'power', value: -2, condition: 'noAdjasentAlly', aimStatus: 'field',
    }],
    img: SinisterFog,
    status: 'hand',
  },
};

// InvisibilityCloak: {
//   name: 'Invisibility cloak',
//   id: _.uniqueId(),
//   type: 'spell',
//   subtype: 'permanent',
//   cost: 1,
//   currentC: 1,
//   featInfo: ['INVISIBILITY'],
//   description: 'InvisibilityCloak',
//   school: 'Shadow',
//   place: 'warrior',
//   features: [
//     {
//       spell: true,
//       attach: ['warrior', 'flyer', 'shooter', 'fighter'],
//       aim: ['warrior', 'flyer', 'shooter', 'fighter'],
//       type: 'good',
//       name: 'invisible',
//       aimStatus: 'field',
//     },
//   ],
//   img: InvisibilityCloak,
//   status: 'hand',
// },
