import _ from 'lodash';
import BattleCry from '@assets/skillsIcons/BattleCry.png';
import DoubleDaggers from '@assets/skillsIcons/DoubleDaggers.png';
import TemplarShield from '@assets/skillsIcons/TemplarShield.png';
import Resistance from '@assets/skillsIcons/Resistance.png';
// import FirstAid from '../../assets/skillsIcons/FirstAid.png';
import LeatherArmor from '@assets/skillsIcons/LeatherArmor.png';
import PlateArmor from '@assets/skillsIcons/PlateArmor.png';
import Leadership from '@assets/skillsIcons/Leadership.png';
import BattleTactics from '@assets/skillsIcons/BattleTactics.png';
import RighteousHammer from '@assets/skillsIcons/RighteousHammer.png';
import WindStaff from '@assets/skillsIcons/WindStaff.png';
import GoldenBow from '@assets/skillsIcons/GoldenBow.png';

export default {
  BattleCry: {
    name: 'BattleCry',
    type: 'spell',
    subtype: 'temporary',
    returnable: false,
    cost: 2,
    currentC: 2,
    skillValue: 0,
    featInfo: ['TEMPORARY'],
    description: 'BattleCry',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: false,
    features: [{
      spell: true,
      attach: ['hero'],
      aim: ['hero'],
      type: 'good',
      name: 'readiness',
      aimStatus: 'field',
    },
    {
      spell: true,
      attach: false,
      aim: ['hero'],
      type: 'good',
      name: 'readiness',
      aimStatus: 'field',
    }],
    img: BattleCry,
    status: 'hand',
    disabled: false,
  },
  MeleeCombat: {
    name: 'MeleeCombat',
    type: 'spell',
    subtype: 'permanent',
    returnable: false,
    cost: 3,
    currentC: 3,
    showCharges: true,
    featInfo: ['ARTEFACT'],
    description: 'MeleeCombat',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    charges: 2,
    curCharges: 2,
    heroSpell: false,
    features: [{
      spell: true,
      attach: ['hero'],
      aim: ['hero'],
      type: 'good',
      name: 'invoke',
      description: 'meleeCombat',
      aimStatus: 'field',
      condition: 'insteadatk',
      charges: 2,
      cost: 0,
      value: {
        img: DoubleDaggers,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        description: 'AddAttackCast',
        school: 'Skills',
        place: '',
        featInfo: [],
        features: [{
          attach: ['warrior', 'fighter', 'shooter', 'flyer'],
          aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
          type: 'good',
          name: 'atkPower',
          value: 2,
          charges: 1,
          aimStatus: 'field',
        }],
        status: 'hand',
      },
    },
    ],
    img: DoubleDaggers,
    status: 'hand',
    disabled: false,
  },
  Protection: {
    name: 'Protection',
    type: 'spell',
    subtype: 'permanent',
    returnable: false,
    cost: 2,
    currentC: 2,
    featInfo: ['PERMANENT'],
    description: 'Protection',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: false,
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter', 'spells'],
      type: 'good',
      name: 'protection',
      token: 'protection',
      value: { type: 'number', val: 1 },
      aimStatus: 'field',
    },
    {
      spell: true,
      attach: ['warrior', 'hero'],
      aim: ['warrior', 'hero', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'retaliateProtect',
      value: { type: 'number', val: 1 },
      aimStatus: 'field',
    }],
    img: TemplarShield,
    status: 'hand',
    disabled: false,
  },
  Resistance: {
    name: 'Resistance',
    type: 'spell',
    subtype: 'instant',
    returnable: false,
    cost: 1,
    currentC: 1,
    featInfo: ['PERMANENT', 'MAGICSHIELD'],
    description: 'Resistance',
    school: 'Skills',
    id: _.uniqueId(),
    place: '',
    token: true,
    heroSpell: false,
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['spell'],
      type: 'good',
      name: 'protection',
      token: 'resistance',
      value: { type: 'percent', val: 0.5 },
      aimStatus: 'field',
    }],
    img: Resistance,
    status: 'hand',
    disabled: false,
  },
  Leadership: {
    name: 'Leadership',
    type: 'spell',
    subtype: 'temporary',
    returnable: false,
    cost: 2,
    currentC: 2,
    featInfo: ['TEMPORARY'],
    description: 'Leadership',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'topSpell',
    heroSpell: false,
    features: [{
      spell: true,
      attach: ['line', 'warrior', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      aim: ['hero', 'warrior', 'fighter', 'shooter', 'flyer'],
      name: 'power',
      value: 1,
      aimStatus: 'field',
    }],
    img: Leadership,
    status: 'hand',
    disabled: false,
  },
  BattleTactics: {
    name: 'BattleTactics',
    type: 'spell',
    subtype: 'temporary',
    returnable: false,
    cost: 3,
    currentC: 3,
    featInfo: ['TEMPORARY', 'SWIFT'],
    description: 'BattleTactics',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'topSpell',
    heroSpell: false,
    features: [{
      spell: true,
      attach: ['line', 'warrior', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      aim: ['line', 'warrior', 'fighter', 'shooter', 'flyer'],
      charges: null,
      name: 'moving',
      aimStatus: 'field',
    }],
    img: BattleTactics,
    status: 'hand',
    disabled: false,
  },
  RighteousHammer: {
    name: 'Righteous Hammer',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: ['ARTEFACT'],
    description: 'RighteousHammer',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    charges: 2,
    curCharges: 2,
    showCharges: true,
    features: [{
      spell: true,
      attach: ['hero'],
      aim: ['hero'],
      type: 'good',
      name: 'invoke',
      description: 'righteousHammer',
      aimStatus: 'field',
      condition: 'insteadatk',
      charges: 2,
      cost: 0,
      value: {
        img: RighteousHammer,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        description: 'RighteousHammerCast',
        school: 'Skills',
        place: '',
        featInfo: [],
        features: [{
          attach: false,
          aim: ['warrior', 'flyer', 'shooter', 'fighter'],
          type: 'bad',
          name: 'attack',
          charges: 1,
          value: 2,
          aimStatus: 'field',
          depend: 'warriorsDiff',
          dependValue: 1,
          school: 'light',
        }],
        status: 'hand',
      },
    }],
    img: RighteousHammer,
    status: 'hand',
    disabled: false,
  },
  WindStaff: {
    name: 'Wind Staff',
    type: 'spell',
    subtype: 'permanent',
    cost: 3,
    currentC: 3,
    featInfo: ['ARTEFACT'],
    description: 'WindStaff',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    charges: 2,
    curCharges: 2,
    showCharges: true,
    features: [{
      spell: true,
      attach: ['hero'],
      aim: ['hero'],
      type: 'good',
      name: 'invoke',
      description: 'windStaff',
      aimStatus: 'field',
      condition: 'insteadatk',
      charges: 2,
      cost: 0,
      value: {
        img: WindStaff,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        description: 'MovingCast',
        school: 'Skills',
        place: '',
        featInfo: [],
        features: [{
          spell: true,
          attach: ['warrior', 'flyer', 'shooter', 'fighter'],
          type: 'all',
          aim: ['warrior', 'flyer', 'shooter', 'fighter'],
          charges: 1,
          name: 'moving',
          aimStatus: 'field',
          immediate: true,
        }],
        status: 'hand',
      },
    }],
    img: WindStaff,
    status: 'hand',
    disabled: false,
  },
  GoldenBow: {
    name: 'Golden Bow',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    charges: 4,
    curCharges: 4,
    showCharges: true,
    featInfo: ['ARTEFACT', 'MASSATTACK'],
    description: 'GoldenBow',
    school: 'Skills',
    place: 'warrior',
    features: [
      {
        spell: true,
        attach: ['hero'],
        aim: ['shooter', 'warrior'],
        type: 'good',
        name: 'massAttack',
        charges: 3,
        aimStatus: 'field',
        cost: 0,
      },
      {
        spell: true,
        attach: ['field', 'warrior'],
        aim: ['shooter', 'warrior'],
        type: 'good',
        name: 'massAttack',
        token: 'massAttack',
        charges: 3,
        aimStatus: 'field',
        cost: 0,
      },
      {
        spell: true,
        attach: ['field', 'warrior'],
        aim: ['shooter', 'warrior'],
        type: 'good',
        name: 'power',
        value: 0,
        charges: 3,
        aimStatus: 'field',
        cost: 0,
      },
    ],
    img: GoldenBow,
    status: 'hand',
  },
  LeatherArmor: {
    name: 'Leather Armor',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    charges: 3,
    curCharges: 3,
    showCharges: true,
    featInfo: ['ARTEFACT'],
    description: 'LeatherArmor',
    school: 'Skills',
    place: 'warrior',
    features: [
      {
        spell: true,
        attach: ['hero'],
        aim: ['fighter', 'shooter', 'flyer', 'warrior'],
        type: 'good',
        name: 'protection',
        token: 'protection',
        charges: 3,
        value: { type: 'number', val: 1 },
        aimStatus: 'field',
        cost: 0,
      },
    ],
    img: LeatherArmor,
    status: 'hand',
  },
  PlateArmor: {
    name: 'Plate Armor',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 4,
    currentC: 4,
    charges: 3,
    curCharges: 3,
    showCharges: true,
    featInfo: ['ARTEFACT'],
    description: 'PlateArmor',
    school: 'Skills',
    place: 'warrior',
    features: [
      {
        spell: true,
        attach: ['hero'],
        aim: ['fighter', 'shooter', 'flyer', 'warrior'],
        type: 'good',
        name: 'protection',
        token: 'protection',
        charges: 3,
        value: { type: 'number', val: 2 },
        aimStatus: 'field',
        cost: 0,
      },
    ],
    img: PlateArmor,
    status: 'hand',
  },
  AddAttackCast: {
    img: DoubleDaggers,
    name: 'fake',
    type: 'spell',
    subtype: 'instant',
    currentC: 0,
    description: 'AddAttackCast',
    school: 'Skills',
    place: '',
    featInfo: [],
    features: [{
      attach: ['warrior'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      type: 'good',
      name: 'power',
      value: 2,
      charges: 1,
      aimStatus: 'field',
    }],
    status: 'hand',
  },
  MovingCast: {
    img: WindStaff,
    name: 'fake',
    type: 'spell',
    subtype: 'instant',
    currentC: 0,
    description: 'MovingCast',
    school: 'Skills',
    place: '',
    featInfo: [],
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'all',
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      charges: 1,
      name: 'moving',
      aimStatus: 'field',
      immediate: true,
    }],
    status: 'hand',
  },
  RighteousHammerCast: {
    img: RighteousHammer,
    name: 'fake',
    type: 'spell',
    subtype: 'instant',
    currentC: 0,
    description: 'RighteousHammerCast',
    school: 'Skills',
    place: '',
    featInfo: [],
    features: [{
      attach: false,
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'bad',
      name: 'attack',
      charges: 1,
      value: 2,
      aimStatus: 'field',
      depend: 'warriorsDiff',
      dependValue: 1,
      school: 'light',
    }],
    status: 'hand',
  },
};

// FirstAid: {
//   name: 'FirstAid',
//   type: 'spell',
//   subtype: 'permanent',
//   returnable: false,
//   cost: 1,
//   currentC: 1,
//   featInfo: ['SKILL', 'HEROABILITY'],
//   description: 'FirstAid',
//   school: 'Skills',
//   id: _.uniqueId(),
//   place: 'warrior',
//   heroSpell: false,
//   features: [{
//     spell: true,
//     name: 'heal',
//     attach: false,
//     aim: ['warrior', 'flyer', 'shooter', 'fighter'],
//     value: 4,
//     aimStatus: 'field',
//     type: 'good',
//   }],
//   img: FirstAid,
//   status: 'hand',
//   disabled: false,
// },

// RangeCombat: {
//   name: 'RangeCombat',
//   type: 'spell',
//   subtype: 'permanent',
//   returnable: false,
//   cost: 2,
//   currentC: 2,
//   featInfo: ['SKILL', 'HEROABILITY'],
//   description: 'RangeCombat',
//   school: 'Skills',
//   id: _.uniqueId(),
//   place: 'warrior',
//   heroSpell: true,
//   features: [{
//     spell: true,
//     attach: ['warrior', 'shooter'],
//     aim: ['warrior', 'flyer', 'shooter', 'fighter'],
//     type: 'good',
//     value: 1,
//     name: 'power',
//     aimStatus: 'field',
//   }],
//   img: RangeCombat,
//   status: 'hand',
//   disabled: false,
// },
// Durability: {
//   name: 'Durability',
//   type: 'spell',
//   subtype: 'temporary',
//   returnable: false,
//   cost: 1,
//   currentC: 1,
//   featInfo: ['SKILL', 'HEROABILITY'],
//   description: 'Durability',
//   school: 'Skills',
//   id: _.uniqueId(),
//   place: 'warrior',
//   heroSpell: false,
//   features: [
//     {
//       spell: true,
//       attach: ['warrior', 'flyer', 'shooter', 'fighter'],
//       aim: ['warrior', 'flyer', 'shooter', 'fighter'],
//       type: 'good',
//       name: 'health',
//       value: 3,
//       aimStatus: 'field',
//     },
//     {
//       spell: true,
//       attach: false,
//       aim: ['warrior'],
//       type: 'good',
//       name: 'health',
//       value: 3,
//       aimStatus: 'field',
//     }],
//   img: Durability,
//   status: 'hand',
//   disabled: false,
// },
