import _ from 'lodash';
import BattleCry from '../../assets/skillsIcons/BattleCry.png';
import MeleeCombat from '../../assets/skillsIcons/MeleeCombat.png';
import RangeCombat from '../../assets/skillsIcons/RangeCombat.png';
import Protection from '../../assets/skillsIcons/Protection.png';
import Resistance from '../../assets/skillsIcons/Resistance.png';
import Durability from '../../assets/skillsIcons/Durability.png';
import FirstAid from '../../assets/skillsIcons/FirstAid.png';
import Leadership from '../../assets/skillsIcons/Leadership.png';
import BattleTactics from '../../assets/skillsIcons/BattleTactics.png';

export default {
  BattleCry: {
    name: 'BattleCry',
    type: 'spell',
    subtype: 'temporary',
    returnable: true,
    cost: 2,
    currentC: 2,
    skillValue: 0,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'BattleCry',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [{
      spell: true,
      attach: ['hero'],
      aim: ['hero'],
      type: 'good',
      name: 'readiness',
      aimStatus: 'field',
    },
    {
      spell: true,
      attach: false,
      aim: ['hero'],
      type: 'good',
      name: 'readiness',
      aimStatus: 'field',
    }],
    img: BattleCry,
    status: 'hand',
    disabled: false,
  },
  MeleeCombat: {
    name: 'MeleeCombat',
    type: 'spell',
    subtype: 'permanent',
    returnable: true,
    cost: 2,
    currentC: 2,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'MeleeCombat',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'good',
      value: 1,
      name: 'power',
      aimStatus: 'field',
    }],
    img: MeleeCombat,
    status: 'hand',
    disabled: false,
  },
  RangeCombat: {
    name: 'RangeCombat',
    type: 'spell',
    subtype: 'permanent',
    returnable: true,
    cost: 2,
    currentC: 2,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'RangeCombat',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [{
      spell: true,
      attach: ['warrior', 'shooter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'good',
      value: 1,
      name: 'power',
      aimStatus: 'field',
    }],
    img: RangeCombat,
    status: 'hand',
    disabled: false,
  },
  Protection: {
    name: 'Protection',
    type: 'spell',
    subtype: 'permanent',
    returnable: true,
    cost: 2,
    currentC: 2,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'Protection',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
      aimStatus: 'field',
    }],
    img: Protection,
    status: 'hand',
    disabled: false,
  },
  Resistance: {
    name: 'Resistance',
    type: 'spell',
    subtype: 'permanent',
    returnable: true,
    cost: 1,
    currentC: 1,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'Resistance',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['spell'],
      type: 'good',
      name: 'protection',
      value: { type: 'percent', val: 0.5 },
      aimStatus: 'field',
    }],
    img: Resistance,
    status: 'hand',
    disabled: false,
  },
  Durability: {
    name: 'Durability',
    type: 'spell',
    subtype: 'permanent',
    returnable: true,
    cost: 2,
    currentC: 2,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'Durability',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [
      {
        spell: true,
        attach: ['warrior', 'flyer', 'shooter', 'fighter'],
        aim: ['warrior', 'flyer', 'shooter', 'fighter'],
        type: 'good',
        name: 'health',
        value: 3,
        aimStatus: 'field',
      },
      {
        spell: true,
        attach: false,
        aim: ['warrior'],
        type: 'good',
        name: 'health',
        value: 3,
        aimStatus: 'field',
      }],
    img: Durability,
    status: 'hand',
    disabled: false,
  },
  FirstAid: {
    name: 'FirstAid',
    type: 'spell',
    subtype: 'permanent',
    returnable: true,
    cost: 2,
    currentC: 2,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'FirstAid',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [{
      spell: true,
      name: 'heal',
      condition: 'onTurnStart',
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'flyer', 'shooter', 'fighter'],
      value: 2,
      aimStatus: 'field',
      type: 'good',
    }],
    img: FirstAid,
    status: 'hand',
    disabled: false,
  },
  Leadership: {
    name: 'Leadership',
    type: 'spell',
    subtype: 'permanent',
    returnable: true,
    cost: 2,
    currentC: 2,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'Leadership',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'warrior',
    heroSpell: true,
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior'],
      type: 'good',
      name: 'swift',
      aimStatus: 'field',
    }],
    img: Leadership,
    status: 'hand',
    disabled: false,
  },
  BattleTactics: {
    name: 'BattleTactics',
    type: 'spell',
    subtype: 'temporary',
    returnable: true,
    cost: 2,
    currentC: 2,
    featInfo: ['SKILL', 'HEROABILITY'],
    description: 'BattleTactics',
    school: 'Skills',
    id: _.uniqueId(),
    place: 'topSpell',
    heroSpell: true,
    features: [{
      spell: true,
      attach: ['line', 'warrior', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      aim: ['warrior', 'fighter', 'shooter', 'flyer'],
      charges: null,
      name: 'moving',
      aimStatus: 'field',
    }],
    img: BattleTactics,
    status: 'hand',
    disabled: false,
  },
};
