/* eslint-disable max-len */
import _ from 'lodash';
import Blizzard from '../../assets/waterSpells/Blizzard.png';
import Frostbite from '../../assets/waterSpells/Frostbite.png';
import FrostTrap from '../../assets/waterSpells/FrostTrap.png';
import IceBlock from '../../assets/waterSpells/IceBlock.png';
import IceSpikes from '../../assets/waterSpells/IceSpikes.png';
import IceWall from '../../assets/waterSpells/IceWall.png';
import IceWeapon from '../../assets/waterSpells/IceWeapon.png';
import Icing from '../../assets/waterSpells/Icing.png';
import Tsunami from '../../assets/waterSpells/Tsunami.png';
import Waterfall from '../../assets/waterSpells/Waterfall.png';
import IceArrow from '../../assets/waterSpells/IceArrow.png';
import IceArmor from '../../assets/waterSpells/IceArmor.png';

export default {
  Blizzard: {
    name: 'Blizzard',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 3,
    currentC: 3,
    featInfo: ['LASTCAST'],
    description: 'Blizzard',
    school: 'Water',
    place: 'midSpell',
    features: [
      {
        spell: true, attach: false, type: 'all', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], value: 3, name: 'attack', aimStatus: 'field', school: 'water',
      },
      {
        spell: true, attach: false, type: 'all', aim: ['row', 'spell', 'warrior', 'fighter', 'shooter', 'flyer'], value: 3, name: 'attack', condition: 'lastcall', aimStatus: 'field', school: 'water',
      },
    ],
    img: Blizzard,
    status: 'hand',
  },
  Frostbite: {
    name: 'Frostbite',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Frostbite',
    school: 'Water',
    place: 'warrior',
    features: [
      {
        spell: true,
        attach: ['warrior', 'flyer', 'shooter', 'fighter'],
        aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
        type: 'bad',
        name: 'power',
        value: -2,
        aimStatus: 'field',
      },
    ],
    img: Frostbite,
    status: 'hand',
  },
  FrostTrap: {
    name: 'Frost trap',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'reaction',
    cost: 1,
    currentC: 1,
    featInfo: ['REACTION'],
    description: 'FrostTrap',
    school: 'Water',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    place: 'bigSpell',
    features: [{
      spell: true, attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onplay', type: 'bad', charges: 1, aimStatus: 'field', cost: 1, subtype: 'reaction',
    },
    {
      spell: true, attach: ['field', 'warrior'], type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 3, charges: 1, condition: 'onplay', aimStatus: 'field', cost: 0, subtype: 'reaction', school: 'water',
    },
    {
      spell: true, attach: ['field', 'warrior'], type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 3, charges: 1, condition: 'onmove', aimStatus: 'field', cost: 0, subtype: 'reaction', school: 'water',
    },
    {
      spell: true, attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onmove', type: 'bad', charges: 1, aimStatus: 'field', cost: 1, subtype: 'reaction',
    }],
    img: FrostTrap,
    status: 'hand',
  },
  IceBlock: {
    name: 'Ice block',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'IceBlock',
    school: 'Water',
    place: 'warrior',
    features: [
      {
        spell: true,
        attach: ['hero'],
        aim: ['hero', 'fighter', 'shooter', 'flyer', 'warrior', 'spell'],
        type: 'good',
        name: 'protection',
        value: { type: 'number', val: 100 },
        aimStatus: 'field',
        cost: 0,
      },
    ],
    img: IceBlock,
    status: 'hand',
  },
  IceSpikes: {
    name: 'Ice spikes',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 4,
    currentC: 4,
    featInfo: ['LASTCAST'],
    description: 'IceSpikes',
    school: 'Water',
    place: 'topSpell',
    features: [{
      spell: true, attach: false, type: 'bad', name: 'attack', value: 2, aim: ['line', 'warrior', 'fighter', 'shooter', 'flyer'], aimStatus: 'field', school: 'water',
    },
    {
      spell: true,
      attach: ['line'],
      type: 'bad',
      aim: ['warrior', 'fighter', 'shooter', 'flyer'],
      name: 'attack',
      condition: 'onmove',
      value: 2,
      aimStatus: 'field',
      school: 'water',
    },
    {
      spell: true,
      attach: ['line'],
      type: 'bad',
      aim: ['warrior', 'fighter', 'shooter', 'flyer'],
      name: 'attack',
      condition: 'onplay',
      value: 2,
      aimStatus: 'field',
      school: 'water',
    }],
    img: IceSpikes,
    status: 'hand',
  },
  IceWall: {
    name: 'Ice wall',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'IceWall',
    school: 'Water',
    place: 'midSpell',
    features: [
      {
        spell: true,
        attach: ['row', 'warrior', 'flyer', 'shooter', 'fighter'],
        type: 'all',
        aim: ['warrior', 'fighter', 'shooter'],
        name: 'unarmed',
        aimStatus: 'field',
      }],
    img: IceWall,
    status: 'hand',
  },
  IceWeapon: {
    name: 'Ice weapon',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 4,
    currentC: 4,
    featInfo: [],
    description: 'IceWeapon',
    school: 'Water',
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      type: 'good',
      name: 'power',
      value: 2,
      aimStatus: 'field',
    }],
    img: IceWeapon,
    status: 'hand',
  },
  Icing: {
    name: 'Icing',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Icing',
    school: 'Water',
    place: 'midSpell',
    features: [
      {
        spell: true,
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'immobile',
        aimStatus: 'field',
      },
      {
        spell: true,
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'unarmed',
        aimStatus: 'field',
      }],
    img: Icing,
    status: 'hand',
  },
  Tsunami: {
    name: 'Tsunami',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 5,
    currentC: 5,
    featInfo: [],
    description: 'Tsunami',
    school: 'Water',
    place: '',
    features: [
      {
        spell: true, attach: false, type: 'all', aim: ['row', 'warrior', 'fighter', 'shooter'], name: 'attack', value: 7, aimStatus: 'field', school: 'water',
      },
      {
        spelll: true, attach: false, type: 'all', aim: ['randomNextRow', 'warrior', 'fighter', 'shooter'], name: 'attack', value: 7, aimStatus: 'field', school: 'water',
      },
    ],
    img: Tsunami,
    status: 'hand',
  },
  Waterfall: {
    name: 'Waterfall',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Waterfall',
    school: 'Water',
    place: 'topSpell',
    features: [{
      spell: true, attach: ['line', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'bad', name: 'atkPower', value: -2, aimStatus: 'field',
    }],
    // condition: 'maxPower', conditionValue: 2,
    img: Waterfall,
    status: 'hand',
  },
  IceArrow: {
    name: 'Ice arrow',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    featInfo: ['STUN'],
    description: 'IceArrow',
    school: 'Water',
    place: '',
    features: [{
      spell: true, attach: false, type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'attack', value: 2, aimStatus: 'field', school: 'water',
    }, {
      spell: true, attach: false, type: 'bad', aim: ['warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', aimStatus: 'field',
    }],
    img: IceArrow,
    status: 'hand',
  },
  IceArmor: {
    name: 'Ice armor',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'IceArmor',
    school: 'Water',
    place: 'warrior',
    features: [{
      spell: true,
      attach: ['warrior', 'hero', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'hero', 'spell', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
      aimStatus: 'field',
    },
    {
      spell: true,
      attach: ['warrior', 'hero'],
      aim: ['warrior', 'hero', 'spell', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'retaliateProtect',
      value: { type: 'number', val: 1 },
      aimStatus: 'field',
    }],
    img: IceArmor,
    status: 'hand',
  },
};
