/* eslint-disable max-len */
import _ from 'lodash';
// Warriors
import EarthGolem from '../assets/AcademiaDeck/EarthGolem.png';
import LivingWall from '../assets/AcademiaDeck/LivingWall.png';
import Gargoyle from '../assets/AcademiaDeck/Gargoyle.png';
import MageApprentice from '../assets/AcademiaDeck/MageApprentice.png';
import Rakshasa from '../assets/AcademiaDeck/Rakshasa.png';
import EnergyElemental from '../assets/AcademiaDeck/EnergyElemental.png';
import FireGolem from '../assets/AcademiaDeck/FireGolem.png';
import GremlinShooter from '../assets/AcademiaDeck/GremlinShooter.png';
import IceElemental from '../assets/AcademiaDeck/IceElemental.png';
import IceGiant from '../assets/AcademiaDeck/IceGiant.png';
import YoungGenie from '../assets/AcademiaDeck/YoungGenie.png';
// Spells
import ArcaneArmor from '../assets/AcademiaDeck/ArcaneArmor.png';
import Blizzard from '../assets/AcademiaDeck/Blizzard.png';
import CursedShackle from '../assets/AcademiaDeck/CursedShackle.png';
import Frostbite from '../assets/AcademiaDeck/Frostbite.png';
import FrostTrap from '../assets/AcademiaDeck/FrostTrap.png';
import IceBlock from '../assets/AcademiaDeck/IceBlock.png';
import IceSpikes from '../assets/AcademiaDeck/IceSpikes.png';
import IceWall from '../assets/AcademiaDeck/IceWall.png';
import IceWeapon from '../assets/AcademiaDeck/IceWeapon.png';
import Icing from '../assets/AcademiaDeck/Icing.png';
import InvisibilityCloak from '../assets/AcademiaDeck/InvisibilityCloak.png';
import SoulDrain from '../assets/AcademiaDeck/SoulDrain.png';
import Teleport from '../assets/AcademiaDeck/Teleport.png';
import TownPortal from '../assets/AcademiaDeck/TownPortal.png';
import Transformation from '../assets/AcademiaDeck/Transformation.png';
import Tsunami from '../assets/AcademiaDeck/Tsunami.png';
import Waterfall from '../assets/AcademiaDeck/Waterfall.png';
import IceArrow from '../assets/AcademiaDeck/IceArrow.png';
import IceArmor from '../assets/AcademiaDeck/IceArmor.png';

export const types = ['beforeturn', 'afterplay', 'protection', 'afterdeath'];

const academiaDeck = [
  {
    name: 'Living wall', type: 'warrior', subtype: 'fighter', power: 2, currentP: 2, health: 5, currentHP: 5, cost: 2, description: 'БОЕЦ. Не может передвигаться и атаковать в свой ход', id: _.uniqueId(), features: [{ name: 'immobile' }, { name: 'unarmed' }], attachments: [], img: LivingWall, status: 'hand', turn: 1,
  },
  {
    name: 'Mage apprentice', type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 4, currentHP: 4, cost: 3, description: 'СТРЕЛОК. Может атаковать любого воина на поле', id: _.uniqueId(), features: [{ name: 'massAttack' }], attachments: [], img: MageApprentice, status: 'hand', turn: 1,
  },
  {
    name: 'Mage apprentice', type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 4, currentHP: 4, cost: 3, description: 'СТРЕЛОК. Может атаковать любого воина на поле', id: _.uniqueId(), features: [{ name: 'massAttack' }], attachments: [], img: MageApprentice, status: 'hand', turn: 1,
  },
  {
    name: 'Gremlin shooter', type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 3, currentHP: 3, cost: 2, description: 'СТРЕЛОК. Имеет ответный удар стрелкам силой 1', id: _.uniqueId(), features: [{ name: 'retaliation', value: 1, aim: ['shooter'] }], attachments: [], img: GremlinShooter, status: 'hand', turn: 1,
  },
  {
    name: 'Ice element',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 3,
    description: 'СТРЕЛОК. Перед смертью, оглушает случайного вражеского воина в шеренге где он стоял',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['closeowcell', 'warrior'], name: 'stun', condition: 'lastcall',
    }],
    attachments: [],
    img: IceElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Ice element',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 3,
    description: 'СТРЕЛОК. Перед смертью, оглушает случайного вражеского воина в шеренге где он стоял',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['closerowcell', 'warrior'], name: 'stun', condition: 'lastcall',
    }],
    attachments: [],
    img: IceElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Earth golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    description: 'БОЕЦ. При входе в игру, вылечить 1 здоровье у прилегающих воинов.',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['adjacent', 'warrior'], name: 'heal', value: 1, condition: 'onplay',
    }],
    attachments: [],
    img: EarthGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Earth golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    description: 'БОЕЦ. При входе в игру, вылечить 1 здоровье у прилегающих воинов.',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['adjacent', 'warrior'], name: 'heal', value: 1, condition: 'onplay',
    }],
    attachments: [],
    img: EarthGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Gargoyle',
    type: 'warrior',
    subtype: 'flyer',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    description: 'Когда Бойцы в свой ход атакуют Гаргулью силой атаки более 1, урон от этих атак снижается на 1 единицу',
    id: _.uniqueId(),
    features: [{
      attach: false,
      aim: ['fighter', 'warrior'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
      condition: 'minPower',
      conditionValue: 2,
    }],
    attachments: [],
    img: Gargoyle,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Gargoyle',
    type: 'warrior',
    subtype: 'flyer',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    description: 'Когда Бойцы в свой ход атакуют Гаргулью силой атаки более 1, урон от этих атак снижается на 1 единицу',
    id: _.uniqueId(),
    features: [{
      attach: false,
      aim: ['fighter', 'warrior'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
      condition: 'minPower',
      conditionValue: 2,
    }],
    attachments: [],
    img: Gargoyle,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Fire golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 3,
    currentP: 3,
    health: 6,
    currentHP: 6,
    cost: 4,
    description: 'БОЕЦ. Перед смертью отнимает 1 здоровье у всех воинов в шеренге в которой он находился',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'all', aim: ['row', 'warrior'], name: 'attack', condition: 'lastcall', value: 1,
    }],
    attachments: [],
    img: FireGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Fire golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 3,
    currentP: 3,
    health: 6,
    currentHP: 6,
    cost: 4,
    description: 'БОЕЦ. Перед смертью отнимает 1 здоровье у всех воинов в шеренге в которой он находился',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'all', aim: ['row', 'warrior'], name: 'attack', condition: 'lastcall', value: 1,
    }],
    attachments: [],
    img: FireGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Rakshasa',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 6,
    currentHP: 6,
    cost: 3,
    description: 'Имеет УВОРОТ.',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['warrior'], name: 'evade', condition: 'nextRowCell',
    }],
    attachments: [],
    img: Rakshasa,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Rakshasa',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 6,
    currentHP: 6,
    cost: 3,
    description: 'Имеет УВОРОТ.',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['warrior'], name: 'evade', condition: 'nextRowCell',
    }],
    attachments: [],
    img: Rakshasa,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Young genie',
    type: 'warrior',
    subtype: 'flyer',
    power: 3,
    currentP: 3,
    health: 4,
    currentHP: 4,
    cost: 3,
    description: 'ЛЕТАЮЩИЙ. Когда входит в игру, может переместить вражеского воина на поле на соседнюю клетку',
    id: _.uniqueId(),
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: YoungGenie,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        cost: 0,
        description: 'Выбрать воина для пермещения',
        place: '',
        features: [{
          attach: false, type: 'bad', aim: ['warrior'], name: 'moverow',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    }],
    attachments: [],
    img: YoungGenie,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Young genie',
    type: 'warrior',
    subtype: 'flyer',
    power: 3,
    currentP: 3,
    health: 4,
    currentHP: 4,
    cost: 3,
    description: 'ЛЕТАЮЩИЙ. Когда входит в игру, может переместить вражеского воина на поле на соседнюю клетку',
    id: _.uniqueId(),
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: YoungGenie,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        cost: 0,
        description: 'Выбрать воина для пермещения',
        place: '',
        features: [{
          attach: false, type: 'bad', aim: ['warrior'], name: 'moverow',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    }],
    attachments: [],
    img: YoungGenie,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Young genie',
    type: 'warrior',
    subtype: 'flyer',
    power: 3,
    currentP: 3,
    health: 4,
    currentHP: 4,
    cost: 3,
    description: 'ЛЕТАЮЩИЙ. Когда входит в игру, может переместить вражеского воина на поле на соседнюю клетку',
    id: _.uniqueId(),
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: YoungGenie,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        cost: 0,
        description: 'Выбрать воина для пермещения',
        place: '',
        features: [{
          attach: false, type: 'bad', aim: ['warrior'], name: 'moverow',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    }],
    attachments: [],
    img: YoungGenie,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Energy elemental',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 5,
    currentHP: 5,
    cost: 4,
    description: 'СТРЕЛОК. При атаке в свой ход по воину, отнимает 2 здоровья у другого вражеского воина в шеренге',
    id: _.uniqueId(),
    features: [{
      name: 'attack', condition: 'onattack', type: 'bad', aim: ['nextrowcell', 'warrior'], value: 2, apply: 'attacked',
    }],
    attachments: [],
    img: EnergyElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Energy elemental',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 5,
    currentHP: 5,
    cost: 4,
    description: 'СТРЕЛОК. При атаке в свой ход по воину, отнимает 2 здоровья у другого вражеского воина в шеренге',
    id: _.uniqueId(),
    features: [{
      name: 'attack', condition: 'onattack', type: 'bad', aim: ['nextrowcell', 'warrior'], value: 2, apply: 'attacked',
    }],
    attachments: [],
    img: EnergyElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Ice giant',
    type: 'warrior',
    subtype: 'fighter',
    power: 4,
    currentP: 4,
    health: 8,
    currentHP: 8,
    cost: 6,
    description: 'БОЕЦ. При входе в игру оглушает всех вражеских воинов в шеренге',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onplay',
    }],
    attachments: [],
    img: IceGiant,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Ice giant',
    type: 'warrior',
    subtype: 'fighter',
    power: 4,
    currentP: 4,
    health: 8,
    currentHP: 8,
    cost: 6,
    description: 'БОЕЦ. При входе в игру оглушает всех вражеских воинов в шеренге',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onplay',
    }],
    attachments: [],
    img: IceGiant,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Arcane armor',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    description: 'РЕАКЦИЯ: Отменить первый урон от базовой атаки в ходу по вашему воину или герою (что будет первым) силой 3 и более',
    id: _.uniqueId(),
    place: 'postponed',
    features: [{
      attach: ['field', 'warrior', 'hero'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'good', name: 'protection', value: { type: 'number', val: 100 }, charges: 1, condition: 'minPower', conditionValue: 3,
    }],
    img: ArcaneArmor,
    status: 'hand',
  },
  {
    name: 'Blizzard',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    description: 'Накладывается на центральную клетку. Отнимает 2 здоровье у всех воинов в этой шеренге. ПОДГОТОВКА: отнять 2 здоровья у всех воинов в шеренге',
    id: _.uniqueId(),
    place: 'midSpell',
    features: [
      {
        attach: false, type: 'all', aim: ['row'], value: 2, name: 'attack',
      },
      {
        attach: false, type: 'all', aim: ['row'], value: 2, name: 'attack', condition: 'lastcall',
      },
    ],
    img: Blizzard,
    status: 'hand',
  },
  {
    name: 'Cursed chackle',
    type: 'spell',
    subtype: 'permanent',
    cost: 3,
    description: 'Накладывается на вражеского воина. После того как этот воин нанес урон в свой ход, нанести такой же урон вражескому герою',
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior'],
        type: 'bad',
        condition: 'onattack',
        name: 'selfheroattack',
        value: 'power',
        apply: 'attacker',
      },
    ],
    img: CursedShackle,
    status: 'hand',
  },
  {
    name: 'Frostbite',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    description: 'Накладывается на воина и отнимает у него -2 базовой атаки',
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior'],
        type: 'bad',
        name: 'power',
        value: -2,
      },
    ],
    img: Frostbite,
    status: 'hand',
  },
  {
    name: 'Frost trap',
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    description: 'РЕАКЦИЯ: вражеский воин, который только сделал шаг или вошел в игру, а также наложенные заклинания отправляются в руки к владельцам в изначальном состоянии',
    id: _.uniqueId(),
    place: 'postponed',
    features: [{
      attach: ['field', 'warrior'], aim: ['warrior'], name: 'return', condition: 'onplay', type: 'bad', charges: 1,
    },
    {
      attach: ['field', 'warrior'], aim: ['warrior'], name: 'return', condition: 'onmove', type: 'bad', charges: 1,
    }],
    img: FrostTrap,
    status: 'hand',
  },
  {
    name: 'Ice block',
    type: 'spell',
    subtype: 'temporary',
    cost: 3,
    description: 'Кладется рядом с полем боя. Поглощает весь урон по герою в течение хода, если поглотился урон в прошлом ходу врага, то ледяной блок отправляется в сток в начале вашего хода',
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        attach: ['hero'],
        aim: ['hero', 'fighter', 'shooter', 'flyer', 'warrior', 'spell'],
        type: 'good',
        name: 'protection',
        value: { type: 'number', val: 100 },
      },
    ],
    img: IceBlock,
    status: 'hand',
  },
  {
    name: 'Ice spikes',
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    description: 'Отнять 2 здоровья у всех воинов на целевой линии',
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'attack', value: 2, aim: ['warrior', 'line'],
    }],
    img: IceSpikes,
    status: 'hand',
  },
  {
    name: 'Ice wall',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    description: 'Кладется центральную клетку. Стрелки и Бойцы в этой шеренге не могут атаковать в свой ход',
    id: _.uniqueId(),
    place: 'midSpell',
    features: [
      {
        attach: ['row', 'warrior'],
        type: 'all',
        aim: ['warrior', 'fighter', 'shooter'],
        name: 'unarmed',
      }],
    img: IceWall,
    status: 'hand',
  },
  {
    name: 'Ice weapon',
    type: 'spell',
    subtype: 'permanent',
    cost: 4,
    description: 'Накладывается на воина. Он получает +2 к базовой атаке',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      attach: ['warrior'],
      aim: ['warrior'],
      type: 'good',
      name: 'power',
      value: 2,
    }],
    img: IceWeapon,
    status: 'hand',
  },
  {
    name: 'Icing',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    description: 'Кладется на центральную клетку. Воины в этой шеренге не могут передвигаться и атаковать в свой ход',
    id: _.uniqueId(),
    place: 'midSpell',
    features: [
      {
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'immobile',
      },
      {
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'unarmed',
      }],
    img: Icing,
    status: 'hand',
  },
  {
    name: 'Invisibility cloak',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    description: 'Накладывается на воина. Он получает НЕВИДИМОСТЬ',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      attach: ['warrior'],
      aim: ['warrior'],
      type: 'good',
      name: 'invisible',
    }],
    img: InvisibilityCloak,
    status: 'hand',
  },
  {
    name: 'Soul drain',
    type: 'spell',
    subtype: 'instant',
    cost: 5,
    description: 'Уничтожить вражеского воина на поле боя',
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'attack', value: 200, aim: ['warrior'],
    }],
    img: SoulDrain,
    status: 'hand',
  },
  {
    name: 'Teleport',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    description: 'Переместить союзного воина на любую свободную клетку (подходящую ему)',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      attach: ['warrior'], type: 'good', aim: ['warrior'], name: 'moving',
    }],
    img: Teleport,
    status: 'hand',
  },
  {
    name: 'Town portal',
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    description: 'Вражеский воин отправляется в руку к владельцу и восстанавливает здоровье (если на воине был эффект, то он возвращается в руку владельцу)',
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'return', aim: ['warrior'],
    }],
    img: TownPortal,
    status: 'hand',
  },
  {
    name: 'Transformation',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    description: 'Воин получает ОГЛУШЕНИЕ и вы можете передвинуть его на соседню клетку',
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'stun', aim: 'warrior',
    }, {
      attach: false, type: 'bad', name: 'moverow', aim: 'warrior',
    }],
    img: Transformation,
    status: 'hand',
  },
  {
    name: 'Tsunami',
    type: 'spell',
    subtype: 'instant',
    cost: 7,
    description: 'Отнять 7 здоровья у всех не летающих воинов на поле боя или 8, если это отложенная способность',
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'all', aim: ['field', 'warrior', 'fighter', 'shooter'], name: 'attack', value: 7, depend: 'postponed', dependValue: 8,
    }],
    img: Tsunami,
    status: 'hand',
  },
  {
    name: 'Waterfall',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    description: 'Кладется рядом с полем боя. Все воины с текущей базовой атакой 2 или меньше не могут атаковать в свой ход',
    id: _.uniqueId(),
    place: 'bigSpell',
    features: [{
      attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'all', name: 'unarmed', condition: 'maxPower', conditionValue: 2,
    }],
    img: Waterfall,
    status: 'hand',
  },
  {
    name: 'Ice arrow',
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    description: 'Отнять 2 здоровья у воина, этот воин получает ОГЛУШЕНИЕ',
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', aim: ['warrior'], name: 'attack', value: 2,
    }, {
      attach: false, type: 'bad', aim: ['warrior'], name: 'stun',
    }],
    img: IceArrow,
    status: 'hand',
  },
  {
    name: 'Ice armor',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    description: 'Накладывается на союзного воина или героя. Во время хода врага, урон от всех атак по этому воину или герою снижается на 1',
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      attach: ['warrior', 'hero'],
      aim: ['warrior', 'hero', 'spell', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
    }],
    img: IceArmor,
    status: 'hand',
  },
];

export default academiaDeck;
