/* eslint-disable max-len */
import _ from 'lodash';
// Warriors
import EarthGolem from '../assets/AcademiaDeck/EarthGolem.png';
import LivingWall from '../assets/AcademiaDeck/LivingWall.png';
import Gargoyle from '../assets/AcademiaDeck/Gargoyle.png';
import MageApprentice from '../assets/AcademiaDeck/MageApprentice.png';
import Rakshasa from '../assets/AcademiaDeck/Rakshasa.png';
import EnergyElemental from '../assets/AcademiaDeck/EnergyElemental.png';
import FireGolem from '../assets/AcademiaDeck/FireGolem.png';
import GremlinShooter from '../assets/AcademiaDeck/GremlinShooter.png';
import IceElemental from '../assets/AcademiaDeck/IceElemental.png';
import IceGiant from '../assets/AcademiaDeck/IceGiant.png';
import YoungGenie from '../assets/AcademiaDeck/YoungGenie.png';
// Spells
import ArcaneArmor from '../assets/AcademiaDeck/ArcaneArmor.png';
import Blizzard from '../assets/AcademiaDeck/Blizzard.png';
import CursedShackle from '../assets/AcademiaDeck/CursedShackle.png';
import Frostbite from '../assets/AcademiaDeck/Frostbite.png';
import FrostTrap from '../assets/AcademiaDeck/FrostTrap.png';
import IceBlock from '../assets/AcademiaDeck/IceBlock.png';
import IceSpikes from '../assets/AcademiaDeck/IceSpikes.png';
import IceWall from '../assets/AcademiaDeck/IceWall.png';
import IceWeapon from '../assets/AcademiaDeck/IceWeapon.png';
import Icing from '../assets/AcademiaDeck/Icing.png';
import InvisibilityCloak from '../assets/AcademiaDeck/InvisibilityCloak.png';
import SoulDrain from '../assets/AcademiaDeck/SoulDrain.png';
import Teleport from '../assets/AcademiaDeck/Teleport.png';
import TownPortal from '../assets/AcademiaDeck/TownPortal.png';
import Transformation from '../assets/AcademiaDeck/Transformation.png';
import Tsunami from '../assets/AcademiaDeck/Tsunami.png';
import Waterfall from '../assets/AcademiaDeck/Waterfall.png';
import IceArrow from '../assets/AcademiaDeck/IceArrow.png';
import IceArmor from '../assets/AcademiaDeck/IceArmor.png';
import academiaInfo from './academiaCardsInfo';

export const types = ['beforeturn', 'afterplay', 'protection', 'afterdeath'];

const academiaDeck = [
  {
    name: 'Living wall', type: 'warrior', subtype: 'fighter', power: 2, currentP: 2, health: 5, currentHP: 5, cost: 2, currentC: 2, description: academiaInfo.LivingWall, id: _.uniqueId(), features: [{ name: 'immobile' }, { name: 'unarmed' }], attachments: [], img: LivingWall, status: 'hand', turn: 1,
  },
  {
    name: 'Mage apprentice', type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 4, currentHP: 4, cost: 3, currentC: 3, description: academiaInfo.MageApprentice, id: _.uniqueId(), features: [{ name: 'massAttack' }], attachments: [], img: MageApprentice, status: 'hand', turn: 1,
  },
  {
    name: 'Mage apprentice', type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 4, currentHP: 4, cost: 3, currentC: 3, description: academiaInfo.MageApprentice, id: _.uniqueId(), features: [{ name: 'massAttack' }], attachments: [], img: MageApprentice, status: 'hand', turn: 1,
  },
  {
    name: 'Gremlin shooter', type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 3, currentHP: 3, cost: 2, currentC: 2, description: academiaInfo.GremlinShooter, id: _.uniqueId(), features: [{ name: 'retaliation', value: 1, aim: ['shooter'] }], attachments: [], img: GremlinShooter, status: 'hand', turn: 1,
  },
  {
    name: 'Ice element',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 3,
    currentC: 3,
    description: academiaInfo.IceElement,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['closerowcell', 'warrior'], name: 'stun', condition: 'lastcall',
    }],
    attachments: [],
    img: IceElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Ice element',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 3,
    currentC: 3,
    description: academiaInfo.IceElement,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['closerowcell', 'warrior'], name: 'stun', condition: 'lastcall',
    }],
    attachments: [],
    img: IceElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Earth golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    currentC: 2,
    description: academiaInfo.EarthGolem,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['adjacent', 'warrior'], name: 'heal', value: 1, condition: 'onplay',
    }],
    attachments: [],
    img: EarthGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Earth golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    currentC: 2,
    description: academiaInfo.EarthGolem,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['adjacent', 'warrior'], name: 'heal', value: 1, condition: 'onplay',
    }],
    attachments: [],
    img: EarthGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Gargoyle',
    type: 'warrior',
    subtype: 'flyer',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    currentC: 2,
    description: academiaInfo.Gargoyle,
    id: _.uniqueId(),
    features: [{
      attach: false,
      aim: ['shooter', 'warrior'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
      condition: 'minPower',
      conditionValue: 2,
    }],
    attachments: [],
    img: Gargoyle,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Gargoyle',
    type: 'warrior',
    subtype: 'flyer',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    currentC: 2,
    description: academiaInfo.Gargoyle,
    id: _.uniqueId(),
    features: [{
      attach: false,
      aim: ['shooter', 'warrior'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
      condition: 'minPower',
      conditionValue: 2,
    }],
    attachments: [],
    img: Gargoyle,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Fire golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 3,
    currentP: 3,
    health: 6,
    currentHP: 6,
    cost: 4,
    currentC: 4,
    description: academiaInfo.FireGolem,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'all', aim: ['row', 'warrior'], name: 'attack', condition: 'lastcall', value: 1,
    }],
    attachments: [],
    img: FireGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Fire golem',
    type: 'warrior',
    subtype: 'fighter',
    power: 3,
    currentP: 3,
    health: 6,
    currentHP: 6,
    cost: 4,
    currentC: 4,
    description: academiaInfo.FireGolem,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'all', aim: ['row', 'warrior'], name: 'attack', condition: 'lastcall', value: 1,
    }],
    attachments: [],
    img: FireGolem,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Rakshasa',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 6,
    currentHP: 6,
    cost: 3,
    currentC: 3,
    description: academiaInfo.Rakshasa,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['warrior'], name: 'evade', condition: 'nextRowCell',
    }],
    attachments: [],
    img: Rakshasa,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Rakshasa',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 6,
    currentHP: 6,
    cost: 3,
    currentC: 3,
    description: academiaInfo.Rakshasa,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'good', aim: ['warrior'], name: 'evade', condition: 'nextRowCell',
    }],
    attachments: [],
    img: Rakshasa,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Young genie',
    type: 'warrior',
    subtype: 'flyer',
    power: 3,
    currentP: 3,
    health: 4,
    currentHP: 4,
    cost: 3,
    currentC: 3,
    description: academiaInfo.YoungGenie,
    id: _.uniqueId(),
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: YoungGenie,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        description: academiaInfo.YoungGenieCast,
        place: '',
        features: [{
          attach: false, type: 'bad', aim: ['warrior'], name: 'moverow',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    }],
    attachments: [],
    img: YoungGenie,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Young genie',
    type: 'warrior',
    subtype: 'flyer',
    power: 3,
    currentP: 3,
    health: 4,
    currentHP: 4,
    cost: 3,
    currentC: 3,
    description: academiaInfo.YoungGenie,
    id: _.uniqueId(),
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: YoungGenie,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        description: academiaInfo.YoungGenieCast,
        place: '',
        features: [{
          attach: false, type: 'bad', aim: ['warrior'], name: 'moverow',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    }],
    attachments: [],
    img: YoungGenie,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Young genie',
    type: 'warrior',
    subtype: 'flyer',
    power: 3,
    currentP: 3,
    health: 4,
    currentHP: 4,
    cost: 3,
    currentC: 3,
    description: academiaInfo.YoungGenie,
    id: _.uniqueId(),
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: YoungGenie,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        description: academiaInfo.YoungGenieCast,
        place: '',
        features: [{
          attach: false, type: 'bad', aim: ['warrior'], name: 'moverow',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    }],
    attachments: [],
    img: YoungGenie,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Energy elemental',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 5,
    currentHP: 5,
    cost: 4,
    currentC: 4,
    description: academiaInfo.EnergyElemental,
    id: _.uniqueId(),
    features: [{
      name: 'attack', condition: 'onattack', type: 'bad', aim: ['nextrowcell', 'warrior'], value: 2, apply: 'attacked',
    }],
    attachments: [],
    img: EnergyElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Energy elemental',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 5,
    currentHP: 5,
    cost: 4,
    currentC: 4,
    description: academiaInfo.EnergyElemental,
    id: _.uniqueId(),
    features: [{
      name: 'attack', condition: 'onattack', type: 'bad', aim: ['nextrowcell', 'warrior'], value: 2, apply: 'attacked',
    }],
    attachments: [],
    img: EnergyElemental,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Ice giant',
    type: 'warrior',
    subtype: 'fighter',
    power: 4,
    currentP: 4,
    health: 8,
    currentHP: 8,
    cost: 6,
    currentC: 6,
    description: academiaInfo.IceGiant,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onplay',
    }],
    attachments: [],
    img: IceGiant,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Ice giant',
    type: 'warrior',
    subtype: 'fighter',
    power: 4,
    currentP: 4,
    health: 8,
    currentHP: 8,
    cost: 6,
    currentC: 6,
    description: academiaInfo.IceGiant,
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onplay',
    }],
    attachments: [],
    img: IceGiant,
    status: 'hand',
    turn: 1,
  },
  {
    name: 'Arcane armor',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    description: academiaInfo.ArcaneArmor,
    id: _.uniqueId(),
    place: 'postponed',
    features: [{
      attach: ['field', 'warrior', 'hero'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'good', name: 'protection', value: { type: 'number', val: 100 }, charges: 1, condition: 'minPower', conditionValue: 3,
    }],
    img: ArcaneArmor,
    status: 'hand',
  },
  {
    name: 'Blizzard',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    description: academiaInfo.Blizzard,
    id: _.uniqueId(),
    place: 'midSpell',
    features: [
      {
        attach: false, type: 'all', aim: ['row'], value: 2, name: 'attack',
      },
      {
        attach: false, type: 'all', aim: ['row', 'spell'], value: 2, name: 'attack', condition: 'lastcall',
      },
    ],
    img: Blizzard,
    status: 'hand',
  },
  {
    name: 'Cursed chackle',
    type: 'spell',
    subtype: 'permanent',
    cost: 3,
    currentC: 3,
    description: academiaInfo.CursedChackle,
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior'],
        type: 'bad',
        condition: 'onattack',
        name: 'selfheroattack',
        value: 'power',
        apply: 'attacker',
      },
    ],
    img: CursedShackle,
    status: 'hand',
  },
  {
    name: 'Frostbite',
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    description: academiaInfo.Frostbite,
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
        type: 'bad',
        name: 'power',
        value: -2,
      },
    ],
    img: Frostbite,
    status: 'hand',
  },
  {
    name: 'Frost trap',
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    description: academiaInfo.FrostTrap,
    id: _.uniqueId(),
    place: 'postponed',
    features: [{
      attach: ['field', 'warrior'], aim: ['warrior'], name: 'return', condition: 'onplay', type: 'bad', charges: 1,
    },
    {
      attach: ['field', 'warrior'], aim: ['warrior'], name: 'return', condition: 'onmove', type: 'bad', charges: 1,
    }],
    img: FrostTrap,
    status: 'hand',
  },
  {
    name: 'Ice block',
    type: 'spell',
    subtype: 'temporary',
    cost: 3,
    currentC: 3,
    description: academiaInfo.IceBlock,
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        attach: ['hero'],
        aim: ['hero', 'fighter', 'shooter', 'flyer', 'warrior', 'spell'],
        type: 'good',
        name: 'protection',
        value: { type: 'number', val: 100 },
      },
    ],
    img: IceBlock,
    status: 'hand',
  },
  {
    name: 'Ice spikes',
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    currentC: 3,
    description: academiaInfo.IceSpikes,
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'attack', value: 2, aim: ['warrior', 'line'],
    }],
    img: IceSpikes,
    status: 'hand',
  },
  {
    name: 'Ice wall',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    description: academiaInfo.IceWall,
    id: _.uniqueId(),
    place: 'midSpell',
    features: [
      {
        attach: ['row', 'warrior'],
        type: 'all',
        aim: ['warrior', 'fighter', 'shooter'],
        name: 'unarmed',
      }],
    img: IceWall,
    status: 'hand',
  },
  {
    name: 'Ice weapon',
    type: 'spell',
    subtype: 'permanent',
    cost: 4,
    currentC: 4,
    description: academiaInfo.IceWeapon,
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      attach: ['warrior'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      type: 'good',
      name: 'power',
      value: 2,
    }],
    img: IceWeapon,
    status: 'hand',
  },
  {
    name: 'Icing',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    description: academiaInfo.Icing,
    id: _.uniqueId(),
    place: 'midSpell',
    features: [
      {
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'immobile',
      },
      {
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'unarmed',
      }],
    img: Icing,
    status: 'hand',
  },
  {
    name: 'Invisibility cloak',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    description: academiaInfo.InvisibilityCloak,
    id: _.uniqueId(),
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior'],
        type: 'good',
        name: 'invisible',
      },
      {
        attach: ['warrior'], type: 'good', name: 'protection', value: { type: 'percent', val: 0.5 }, aim: ['spell'],
      },
    ],
    img: InvisibilityCloak,
    status: 'hand',
  },
  {
    name: 'Soul drain',
    type: 'spell',
    subtype: 'instant',
    cost: 5,
    currentC: 5,
    description: academiaInfo.SoulDrain,
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'attack', value: 200, aim: ['warrior'],
    }],
    img: SoulDrain,
    status: 'hand',
  },
  {
    name: 'Teleport',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    description: academiaInfo.Teleport,
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: ['warrior'], type: 'good', aim: ['warrior'], charges: 1, name: 'moving',
    }],
    img: Teleport,
    status: 'hand',
  },
  {
    name: 'Town portal',
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    currentC: 3,
    description: academiaInfo.TownPortal,
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'return', aim: ['warrior'],
    }],
    img: TownPortal,
    status: 'hand',
  },
  {
    name: 'Transformation',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    description: academiaInfo.Transformation,
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'stun', aim: 'warrior',
    }, {
      attach: false, type: 'bad', name: 'moverow', aim: 'warrior',
    }],
    img: Transformation,
    status: 'hand',
  },
  {
    name: 'Tsunami',
    type: 'spell',
    subtype: 'instant',
    cost: 7,
    currentC: 7,
    description: academiaInfo.Tsunami,
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'all', aim: ['field', 'warrior', 'fighter', 'shooter'], name: 'attack', value: 7, depend: 'postponed', dependValue: 8,
    }],
    img: Tsunami,
    status: 'hand',
  },
  {
    name: 'Waterfall',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    description: academiaInfo.Waterfall,
    id: _.uniqueId(),
    place: 'bigSpell',
    features: [{
      attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'all', name: 'unarmed', condition: 'maxPower', conditionValue: 2,
    }],
    img: Waterfall,
    status: 'hand',
  },
  {
    name: 'Ice arrow',
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    description: academiaInfo.IceArrow,
    id: _.uniqueId(),
    place: '',
    features: [{
      attach: false, type: 'bad', aim: ['warrior'], name: 'attack', value: 2,
    }, {
      attach: false, type: 'bad', aim: ['warrior'], name: 'stun',
    }],
    img: IceArrow,
    status: 'hand',
  },
  {
    name: 'Ice armor',
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    description: academiaInfo.IceArmor,
    id: _.uniqueId(),
    place: 'warrior',
    features: [{
      attach: ['warrior', 'hero'],
      aim: ['warrior', 'hero', 'spell', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
    }],
    img: IceArmor,
    status: 'hand',
  },
];

export default academiaDeck;
