import _ from 'lodash';
import Blizzard from '../assets/AcademiaDeck/Blizzard.png';
import Frostbite from '../assets/AcademiaDeck/Frostbite.png';
import FrostTrap from '../assets/AcademiaDeck/FrostTrap.png';
import IceBlock from '../assets/AcademiaDeck/IceBlock.png';
import IceSpikes from '../assets/AcademiaDeck/IceSpikes.png';
import IceWall from '../assets/AcademiaDeck/IceWall.png';
import IceWeapon from '../assets/AcademiaDeck/IceWeapon.png';
import Icing from '../assets/AcademiaDeck/Icing.png';
import Tsunami from '../assets/AcademiaDeck/Tsunami.png';
import Waterfall from '../assets/AcademiaDeck/Waterfall.png';
import IceArrow from '../assets/AcademiaDeck/IceArrow.png';
import IceArmor from '../assets/AcademiaDeck/IceArmor.png';

export default {
  Blizzard: {
    name: 'Blizzard',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: ['LASTCAST'],
    description: 'Blizzard',
    faction: 'Academia',
    school: 'Water',
    place: 'midSpell',
    features: [
      {
        attach: false, type: 'all', aim: ['row'], value: 2, name: 'attack',
      },
      {
        attach: false, type: 'all', aim: ['row', 'spell'], value: 2, name: 'attack', condition: 'lastcall',
      },
    ],
    img: Blizzard,
    status: 'hand',
  },
  Frostbite: {
    name: 'Frostbite',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Frostbite',
    faction: 'Academia',
    school: 'Water',
    place: 'warrior',
    features: [
      {
        attach: ['warrior'],
        aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
        type: 'bad',
        name: 'power',
        value: -2,
      },
    ],
    img: Frostbite,
    status: 'hand',
  },
  FrostTrap: {
    name: 'Frost trap',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    featInfo: ['REACTION'],
    description: 'FrostTrap',
    faction: 'Academia',
    school: 'Water',
    place: 'postponed',
    features: [{
      attach: ['field', 'warrior'], aim: ['warrior'], name: 'return', condition: 'onplay', type: 'bad', charges: 1,
    },
    {
      attach: ['field', 'warrior'], aim: ['warrior'], name: 'return', condition: 'onmove', type: 'bad', charges: 1,
    }],
    img: FrostTrap,
    status: 'hand',
  },
  IceBlock: {
    name: 'Ice block',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'IceBlock',
    faction: 'Academia',
    school: 'Water',
    place: 'warrior',
    features: [
      {
        attach: ['hero'],
        aim: ['hero', 'fighter', 'shooter', 'flyer', 'warrior', 'spell'],
        type: 'good',
        name: 'protection',
        value: { type: 'number', val: 100 },
      },
    ],
    img: IceBlock,
    status: 'hand',
  },
  IceSpikes: {
    name: 'Ice spikes',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'IceSpikes',
    faction: 'Academia',
    school: 'Water',
    place: '',
    features: [{
      attach: false, type: 'bad', name: 'attack', value: 2, aim: ['warrior', 'line'],
    }],
    img: IceSpikes,
    status: 'hand',
  },
  IceWall: {
    name: 'Ice wall',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'IceWall',
    faction: 'Academia',
    school: 'Water',
    place: 'midSpell',
    features: [
      {
        attach: ['row', 'warrior'],
        type: 'all',
        aim: ['warrior', 'fighter', 'shooter'],
        name: 'unarmed',
      }],
    img: IceWall,
    status: 'hand',
  },
  IceWeapon: {
    name: 'Ice weapon',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'permanent',
    cost: 4,
    currentC: 4,
    featInfo: [],
    description: 'IceWeapon',
    faction: 'Academia',
    school: 'Water',
    place: 'warrior',
    features: [{
      attach: ['warrior'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer', 'hero'],
      type: 'good',
      name: 'power',
      value: 2,
    }],
    img: IceWeapon,
    status: 'hand',
  },
  Icing: {
    name: 'Icing',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Icing',
    faction: 'Academia',
    school: 'Water',
    place: 'midSpell',
    features: [
      {
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'immobile',
      },
      {
        attach: ['row', 'warrior'],
        aim: ['fighter', 'shooter', 'flyer'],
        type: 'all',
        name: 'unarmed',
      }],
    img: Icing,
    status: 'hand',
  },
  Tsunami: {
    name: 'Tsunami',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 7,
    currentC: 7,
    featInfo: [],
    description: 'Tsunami',
    faction: 'Academia',
    school: 'Water',
    place: '',
    features: [{
      attach: false, type: 'all', aim: ['field', 'warrior', 'fighter', 'shooter'], name: 'attack', value: 7, depend: 'postponed', dependValue: 8,
    }],
    img: Tsunami,
    status: 'hand',
  },
  Waterfall: {
    name: 'Waterfall',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: [],
    description: 'Waterfall',
    faction: 'Academia',
    school: 'Water',
    place: 'bigSpell',
    features: [{
      attach: ['field', 'warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'all', name: 'unarmed', condition: 'maxPower', conditionValue: 2,
    }],
    img: Waterfall,
    status: 'hand',
  },
  IceArrow: {
    name: 'Ice arrow',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    featInfo: ['STUN'],
    description: 'IceArrow',
    faction: 'Academia',
    school: 'Water',
    place: '',
    features: [{
      attach: false, type: 'bad', aim: ['warrior'], name: 'attack', value: 2,
    }, {
      attach: false, type: 'bad', aim: ['warrior'], name: 'stun',
    }],
    img: IceArrow,
    status: 'hand',
  },
  IceArmor: {
    name: 'Ice armor',
    id: _.uniqueId(),
    type: 'spell',
    subtype: 'temporary',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'IceArmor',
    faction: 'Academia',
    school: 'Water',
    place: 'warrior',
    features: [{
      attach: ['warrior', 'hero'],
      aim: ['warrior', 'hero', 'spell', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
    },
    {
      attach: ['warrior', 'hero'],
      aim: ['warrior', 'hero', 'spell', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'retaliateProtect',
      value: { type: 'number', val: 1 },
    }],
    img: IceArmor,
    status: 'hand',
  },
};
