/* eslint-disable max-len */
import _ from 'lodash';
// Warriors
import EarthGolem from '../../assets/academiaCards/EarthGolem.png';
import LivingWall from '../../assets/academiaCards/LivingWall.png';
import Gargoyle from '../../assets/academiaCards/Gargoyle.png';
import MageApprentice from '../../assets/academiaCards/MageApprentice.png';
import Rakshasa from '../../assets/academiaCards/Rakshasa.png';
import EnergyElemental from '../../assets/academiaCards/EnergyElemental.png';
import FireGolem from '../../assets/academiaCards/FireGolem.png';
import GremlinShooter from '../../assets/academiaCards/GremlinShooter.png';
import IceElemental from '../../assets/academiaCards/IceElemental.png';
import IceGiant from '../../assets/academiaCards/IceGiant.png';
import YoungGenie from '../../assets/academiaCards/YoungGenie.png';
import NalaHero from '../../assets/academiaCards/NalaHero.png';
import AstralHero from '../../assets/academiaCards/AstralHero.png';

// Spells
import Wisdom from '../../assets/academiaCards/Wisdom.png';
import IntellectPower from '../../assets/academiaCards/IntellectPower.png';
import ForgottenSpell from '../../assets/academiaCards/ForgottenSpell.png';
import PowerChannel from '../../assets/academiaCards/PowerChannel.png';

export const types = ['beforeturn', 'afterplay', 'protection', 'afterdeath'];

const academiaDeck = {
  NalaHero: {
    name: 'Nala-Hero',
    type: 'hero',
    subtype: 'hero',
    faction: 'Academia',
    health: 20,
    currentHP: 20,
    featInfo: [],
    description: 'NalaHero',
    id: _.uniqueId(),
    cellId: '',
    cost: 2,
    currentC: 2,
    place: '',
    spellSchools: ['Water', 'Shadow', 'Skills'],
    attachments: [],
    features: [{
      attach: false, type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'attack', value: 1, aimStatus: 'field',
    },
    {
      attach: false, type: 'all', aim: ['warrior'], name: 'drawCard', condition: 'insteadatk', cost: 1, description: 'drawCard',
    }],
    img: NalaHero,
    status: 'field',
    turn: 0,
  },
  AstralHero: {
    name: 'Astral-Hero',
    type: 'hero',
    subtype: 'hero',
    faction: 'Academia',
    health: 20,
    currentHP: 20,
    featInfo: [],
    description: 'AstralHero',
    id: _.uniqueId(),
    cellId: '',
    cost: 3,
    currentC: 3,
    place: '',
    spellSchools: ['Fire', 'Shadow', 'Skills'],
    attachments: [],
    features: [{
      spell: true, attach: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'good', aim: ['warrior', 'flyer', 'shooter', 'fighter'], charges: 1, name: 'moving', aimStatus: 'field', immediate: true,
    },
    {
      attach: false, type: 'all', aim: ['warrior'], name: 'drawCard', condition: 'insteadatk', cost: 1, description: 'drawCard',
    }],
    img: AstralHero,
    status: 'field',
    turn: 0,
  },
  LivingWall: {
    name: 'Living wall', id: _.uniqueId(), type: 'warrior', subtype: 'fighter', power: 2, currentP: 2, health: 5, currentHP: 5, cost: 2, currentC: 2, featInfo: ['FIGHTER', 'IMMOBILIZED'], description: 'LivingWall', faction: 'Academia', features: [{ name: 'immobile' }, { name: 'unarmed' }], attachments: [], img: LivingWall, status: 'deck', turn: 1,
  },
  MageApprentice: {
    name: 'Mage apprentice', id: _.uniqueId(), type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 4, currentHP: 4, cost: 3, currentC: 3, featInfo: ['SHOOTER', 'MAGICSHIELD'], description: 'MageApprentice', faction: 'Academia', features: [{ name: 'protection', value: { type: 'percent', val: 0.5 }, aim: ['spell'] }], attachments: [], img: MageApprentice, status: 'deck', turn: 1,
  },
  GremlinShooter: {
    name: 'Gremlin shooter', id: _.uniqueId(), type: 'warrior', subtype: 'shooter', power: 2, currentP: 2, health: 3, currentHP: 3, cost: 2, currentC: 2, featInfo: ['SHOOTER'], description: 'GremlinShooter', faction: 'Academia', features: [{ name: 'retaliation', value: 1, aim: ['shooter'] }], attachments: [], img: GremlinShooter, status: 'deck', turn: 1,
  },
  IceElement: {
    name: 'Ice element',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 3,
    currentC: 3,
    featInfo: ['SHOOTER'],
    description: 'IceElement',
    faction: 'Academia',
    features: [{
      attach: false, type: 'bad', aim: ['closestEnemyInRow', 'warrior', 'flyer', 'shooter', 'fighter'], name: 'stun', condition: 'lastcall', aimStatus: 'field',
    }],
    attachments: [],
    img: IceElemental,
    status: 'hand',
    turn: 1,
  },
  EarthGolem: {
    name: 'Earth golem',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 4,
    currentHP: 4,
    cost: 2,
    currentC: 2,
    featInfo: ['FIGHTER', 'PROTECTOR'],
    description: 'EarthGolem',
    faction: 'Academia',
    features: [
      {
        attach: ['row'], type: 'good', name: 'redirectWarAttack', aim: ['warrior', 'fighter', 'shooter', 'flyer'], status: 'field', attachCondition: 'cardInFrontLine',
      },
    ],
    attachments: [],
    img: EarthGolem,
    status: 'hand',
    turn: 1,
  },
  Gargoyle: {
    name: 'Gargoyle',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'flyer',
    power: 2,
    currentP: 2,
    health: 3,
    currentHP: 3,
    cost: 2,
    currentC: 2,
    featInfo: ['FLYER'],
    description: 'Gargoyle',
    faction: 'Academia',
    features: [{
      spell: true,
      attach: false,
      aim: ['shooter', 'warrior'],
      type: 'good',
      name: 'protection',
      value: { type: 'number', val: 1 },
      condition: 'minPower',
      conditionValue: 2,
      aimStatus: 'field',
    }],
    attachments: [],
    img: Gargoyle,
    status: 'hand',
    turn: 1,
  },
  FireGolem: {
    name: 'Fire golem',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'fighter',
    power: 3,
    currentP: 3,
    health: 6,
    currentHP: 6,
    cost: 4,
    currentC: 4,
    featInfo: ['FIGHTER', 'LASTCAST'],
    description: 'FireGolem',
    faction: 'Academia',
    features: [{
      spell: true, attach: false, type: 'all', aim: ['row', 'warrior', 'flyer', 'shooter', 'fighter'], name: 'attack', condition: 'lastcall', value: 1, aimStatus: 'field',
    }],
    attachments: [],
    img: FireGolem,
    status: 'hand',
    turn: 1,
  },
  Rakshasa: {
    name: 'Rakshasa',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    health: 6,
    currentHP: 6,
    cost: 3,
    currentC: 3,
    featInfo: ['FIGHTER', 'EVASION'],
    description: 'Rakshasa',
    faction: 'Academia',
    features: [{
      attach: false, type: 'good', aim: ['warrior'], name: 'evade', condition: 'nextRowCell', aimStatus: 'field',
    }],
    attachments: [],
    img: Rakshasa,
    status: 'hand',
    turn: 1,
  },
  YoungGenie: {
    name: 'Young genie',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'flyer',
    power: 3,
    currentP: 3,
    health: 5,
    currentHP: 5,
    cost: 4,
    currentC: 4,
    featInfo: ['FLYER'],
    description: 'YoungGenie',
    faction: 'Academia',
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: YoungGenie,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        featInfo: [],
        description: 'YoungGenieCast',
        faction: 'Academia',
        ownerId: '',
        place: '',
        features: [{
          attach: ['warrior'], type: 'all', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'moveNextRow', charges: 1, immediate: true, aimStatus: 'field',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    }],
    attachments: [],
    img: YoungGenie,
    status: 'hand',
    turn: 1,
  },
  EnergyElemental: {
    name: 'Energy elemental',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    health: 5,
    currentHP: 5,
    cost: 4,
    currentC: 4,
    featInfo: ['SHOOTER', 'PIERCING'],
    description: 'EnergyElemental',
    faction: 'Academia',
    features: [{
      name: 'attack', condition: 'onattack', type: 'bad', aim: ['otherWarInRow', 'warrior', 'flyer', 'shooter', 'fighter'], value: 2, apply: 'attacked', aimStatus: 'field',
    }],
    attachments: [],
    img: EnergyElemental,
    status: 'hand',
    turn: 1,
  },
  IceGiant: {
    name: 'Ice giant',
    id: _.uniqueId(),
    type: 'warrior',
    subtype: 'fighter',
    power: 4,
    currentP: 4,
    health: 8,
    currentHP: 8,
    cost: 6,
    currentC: 6,
    featInfo: ['FIGHTER'],
    description: 'IceGiant',
    faction: 'Academia',
    features: [{
      attach: false, type: 'bad', aim: ['row', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onplay', aimStatus: 'field',
    },
    {
      attach: false, type: 'good', aim: ['otherAllyInRow', 'warrior', 'fighter', 'shooter', 'flyer'], name: 'stun', condition: 'onplay', aimStatus: 'field',
    }],
    attachments: [],
    img: IceGiant,
    status: 'hand',
    turn: 1,
  },
  Wisdom: {
    name: 'Wisdom',
    type: 'spell',
    subtype: 'instant',
    cost: 3,
    currentC: 3,
    featInfo: [],
    description: 'Wisdom',
    faction: 'Academia',
    id: _.uniqueId(),
    place: 'graveyard',
    turn: 0,
    heroSpell: false,
    features: [{
      spell: true,
      attach: ['grave'],
      type: 'good',
      aim: ['spell', 'permanent', 'instant', 'temporary', 'reaction'],
      name: 'ressurect',
      resCost: 0,
      aimStatus: 'graveyard',
    }],
    img: Wisdom,
    status: 'hand',
    disabled: false,
  },
  IntellectPower: {
    name: 'IntellectPower',
    type: 'spell',
    subtype: 'reaction',
    cost: 3,
    currentC: 3,
    featInfo: ['REACTION'],
    description: 'IntellectPower',
    faction: 'Academia',
    id: _.uniqueId(),
    place: 'bigSpell',
    charges: 1,
    curCharges: 1,
    showCharges: false,
    features: [
      {
        spell: true,
        attach: ['field', 'hero'],
        aim: ['warrior', 'fighter', 'shooter', 'flyer', 'spell', 'hero'],
        type: 'good',
        condition: 'gotAttacked',
        name: 'increasePoints',
        value: 6,
        charges: 1,
        aimStatus: 'field',
        cost: 3,
        subtype: 'reaction',
      }],
    img: IntellectPower,
    status: 'hand',
    disabled: false,
  },
  ForgottenSpell: {
    name: 'ForgottenSpell',
    type: 'spell',
    subtype: 'instant',
    cost: 1,
    currentC: 1,
    featInfo: [],
    description: 'ForgottenSpell',
    faction: 'Academia',
    id: _.uniqueId(),
    heroSpell: false,
    place: 'spell',
    features: [{
      spell: true,
      attach: false,
      type: 'bad',
      name: 'cleanSpell',
      aim: ['spell', 'permanent', 'temporary'],
      aimStatus: 'field',
    }],
    img: ForgottenSpell,
    status: 'hand',
    disabled: false,
  },
  PowerChannel: {
    name: 'PowerChannel',
    type: 'spell',
    subtype: 'instant',
    cost: 6,
    currentC: 6,
    featInfo: [],
    description: 'PowerChannel',
    faction: 'Academia',
    id: _.uniqueId(),
    heroSpell: false,
    features: [
      {
        attach: false,
        ability: true,
        type: 'all',
        aim: [],
        name: 'stealPoints',
        condition: 'insteadatk',
        description: 'stealPoints',
        value: { owner: 0, enemy: 10 },
        cost: 6,
      }],
    img: PowerChannel,
    status: 'hand',
    disabled: false,
  },
};

export default academiaDeck;

// { name: 'massAttack' },
