/* eslint-disable max-len */
import _ from 'lodash';
import BannerMan from '@assets/castleCards/Bannerman.png';
import Defender from '@assets/castleCards/Defender.png';
import ImperialGriffon from '@assets/castleCards/ImperialGriffon.png';
import ImperialShooter from '@assets/castleCards/ImperialShooter.png';
import KnightGuardian from '@assets/castleCards/KnightGuardian.png';
import MasterOfLight from '@assets/castleCards/MasterOfLight.png';
import MasterShooter from '@assets/castleCards/MasterShooter.png';
import TemplarChampion from '@assets/castleCards/TemplarChampion.png';
import ValorKnight from '@assets/castleCards/ValorKnight.png';
import WarriorOfLight from '@assets/castleCards/WarriorOfLight.png';
import YoungPriestess from '@assets/castleCards/YoungPriestess.png';
import Marksman from '@assets/castleCards/Marksman.png';
import RighteousFighter from '@assets/castleCards/RighteousFighter.png';
import ZigfridHero from '@assets/castleCards/ZigfridHero.png';
import RetributionSword from '@assets/castleCards/RetributionSword.png';
import AgielHero from '@assets/castleCards/AgielHero.png';
import GoodMorale from '@assets/GoodMorale.png';

// SPELLS
import RetaliationHammer from '../../assets/castleCards/RetaliationHammer.png';
import YouthFountain from '../../assets/castleCards/YouthFountain.png';

const castleDeck = {
  ZigfridHero: {
    name: 'Zigfrid-Hero',
    type: 'hero',
    subtype: 'hero',
    faction: 'Castle',
    health: 20,
    currentHP: 20,
    featInfo: [],
    description: 'ZigfridHero',
    id: _.uniqueId(),
    cellId: '',
    cost: 4,
    currentC: 4,
    place: '',
    spellSchools: ['Air', 'Light', 'Skills'],
    attachments: [],
    features: [{
      attach: false, type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'attack', value: 1, aimStatus: 'field', school: 'light',
    }, {
      attach: ['warrior'], type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'moveNextRow', charges: 1, immediate: true, aimStatus: 'field',
    },
    {
      attach: false, type: 'all', aim: ['warrior'], name: 'drawCard', condition: 'insteadatk', cost: 1, description: 'drawCard',
    },
    ],
    img: ZigfridHero,
    status: 'field',
    turn: 0,
  },
  AgielHero: {
    name: 'Agiel-Hero',
    type: 'hero',
    subtype: 'hero',
    faction: 'Castle',
    health: 20,
    currentHP: 20,
    featInfo: [],
    description: 'AgielHero',
    id: _.uniqueId(),
    cellId: '',
    cost: 4,
    currentC: 4,
    place: '',
    spellSchools: ['Fire', 'Light', 'Skills'],
    attachments: [],
    features: [{
      attach: false, type: 'good', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'heal', value: 2, aimStatus: 'field',
    },
    {
      attach: false, type: 'all', aim: ['warrior'], name: 'drawCard', condition: 'insteadatk', cost: 1, description: 'drawCard',
    },
    ],
    img: AgielHero,
    status: 'field',
    turn: 0,
  },
  ImperialShooter: {
    name: 'Imperial Shooter',
    type: 'warrior',
    subtype: 'shooter',
    power: 1,
    currentP: 1,
    defPower: 0,
    currentDP: 0,
    health: 2,
    currentHP: 2,
    cost: 1,
    currentC: 1,
    justDeployed: true,
    featInfo: [],
    description: 'ImperialShooter',
    faction: 'Castle',
    features: [{
      attach: false, name: 'getCardCopy', condition: 'onplay', cardName: 'ImperialShooter', type: 'good', aim: ['warrior'],
    },
    {
      token: 'shooter',
    }],
    attachments: [],
    img: ImperialShooter,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  MasterShooter: {
    name: 'Master Shooter',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    defPower: 1,
    currentDP: 1,
    health: 4,
    currentHP: 4,
    cost: 3,
    currentC: 3,
    justDeployed: true,
    featInfo: ['RETRIBUTION'],
    description: 'MasterShooter',
    faction: 'Castle',
    features: [{
      spell: true, name: 'retribution', depend: 'attackerPower', aim: ['warrior', 'flyer', 'fighter'],
    },
    {
      token: 'shooter',
    }],
    attachments: [],
    img: MasterShooter,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  Marksman: {
    name: 'Marksman',
    type: 'warrior',
    subtype: 'shooter',
    power: 2,
    currentP: 2,
    defPower: 0,
    currentDP: 0,
    health: 5,
    currentHP: 5,
    cost: 4,
    currentC: 4,
    justDeployed: true,
    featInfo: [],
    description: 'Marksman',
    faction: 'Castle',
    features: [{
      attach: false, type: 'bad', aim: ['closestEnemyInRow', 'warrior', 'flyer', 'shooter', 'fighter'], name: 'attack', value: 3, condition: 'insteadatk', cost: 0, description: 'enchancedShot', aimStatus: 'field', school: 'light',
    },
    {
      token: 'shooter',
    }],
    attachments: [],
    img: Marksman,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  YoungPriestess: {
    name: 'Young Priestess',
    type: 'warrior',
    subtype: 'shooter',
    power: 1,
    currentP: 1,
    defPower: 0,
    currentDP: 0,
    health: 4,
    currentHP: 4,
    cost: 2,
    currentC: 2,
    justDeployed: true,
    featInfo: ['STARTTURN'],
    description: 'YoungPriestess',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [{
      name: 'heal',
      condition: 'onTurnStart',
      aim: ['oneAdjacent', 'warrior', 'flyer', 'shooter', 'fighter'],
      value: 2,
      aimStatus: 'field',
      type: 'good',
    },
    {
      token: 'shooter',
    }],
    attachments: [],
    img: YoungPriestess,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  WarriorOfLight: {
    name: 'Warrior Of Light',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    defPower: 1,
    currentDP: 1,
    health: 4,
    currentHP: 4,
    cost: 2,
    currentC: 2,
    justDeployed: true,
    featInfo: [],
    description: 'WarriorOfLight',
    faction: 'Castle',
    features: [{ name: 'swift', token: 'swift' }],
    attachments: [],
    img: WarriorOfLight,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  ValorKnight: {
    name: 'Valor Knight',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    defPower: 1,
    currentDP: 1,
    health: 5,
    currentHP: 5,
    cost: 3,
    currentC: 3,
    justDeployed: true,
    featInfo: [],
    description: 'ValorKnight',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [{
      name: 'heal', condition: 'onattack', type: 'good', aim: ['nextWarsInLine', 'warrior', 'fighter', 'shooter', 'flyer'], value: 2, aimStatus: 'field',
    }],
    attachments: [],
    img: ValorKnight,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  Bannerman: {
    name: 'Bannerman',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    defPower: 2,
    currentDP: 2,
    health: 5,
    currentHP: 5,
    cost: 3,
    currentC: 3,
    justDeployed: true,
    featInfo: [],
    description: 'Bannerman',
    faction: 'Castle',
    id: _.uniqueId(),
    attachments: [],
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: BannerMan,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        featInfo: [],
        description: 'BannermanCast',
        faction: 'Castle',
        place: '',
        features: [{
          attach: ['warrior', 'fighter', 'shooter', 'flyer'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'good', name: 'power', value: 2, charges: 1, id: _.uniqueId(), aimStatus: 'field',
        }],
        status: 'hand',
      },
      condition: 'onplay',
      aimStatus: 'field',
    }],
    img: BannerMan,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  Defender: {
    name: 'Defender',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    defPower: 2,
    currentDP: 2,
    health: 5,
    currentHP: 5,
    cost: 3,
    currentC: 3,
    justDeployed: true,
    featInfo: [],
    description: 'Defender',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [
      {
        attach: ['field', 'hero'], type: 'good', name: 'protection', token: 'protection', value: { type: 'number', val: 1 }, aim: ['warrior', 'fighter', 'shooter', 'flyer', 'spells'], aimStatus: 'field',
      },
      {
        attach: ['field', 'hero'], type: 'good', name: 'attack', value: 1, aim: ['warrior', 'fighter', 'shooter', 'flyer', 'spells', 'redirectToCaster'], aimStatus: 'field', condition: 'gotAttacked', apply: 'attacked',
      }],
    attachments: [],
    img: Defender,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  RighteousFighter: {
    name: 'Righteous Fighter',
    type: 'warrior',
    subtype: 'fighter',
    power: 3,
    currentP: 3,
    defPower: 1,
    currentDP: 1,
    health: 5,
    currentHP: 5,
    cost: 3,
    currentC: 3,
    justDeployed: true,
    featInfo: [],
    description: 'RighteousFighter',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [
      { name: 'power', value: 1, aim: ['hero'] },
    ],
    attachments: [],
    img: RighteousFighter,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  KnightGuardian: {
    name: 'Knight Guardian',
    type: 'warrior',
    subtype: 'fighter',
    power: 2,
    currentP: 2,
    defPower: 2,
    currentDP: 2,
    health: 8,
    currentHP: 8,
    cost: 4,
    currentC: 4,
    justDeployed: true,
    featInfo: ['PROTECTOR'],
    description: 'KnightGuardian',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [
      {
        attach: ['row'],
        type: 'good',
        name: 'redirectWarAttack',
        aim: ['warrior', 'fighter', 'shooter', 'flyer'],
        status: 'field',
        attachCondition: 'cardInFrontLine',
      },
    //   {
    //   attach: ['nextcells'], type: 'good', name: 'redirectWarAttack', aim: ['warrior', 'fighter', 'shooter', 'flyer'], status: 'field',
    // }
    ],
    attachments: [],
    img: KnightGuardian,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  ImperialGriffon: {
    name: 'Imperial Griffon',
    type: 'warrior',
    subtype: 'flyer',
    power: 2,
    currentP: 2,
    defPower: 3,
    currentDP: 3,
    health: 6,
    currentHP: 6,
    cost: 4,
    currentC: 4,
    justDeployed: true,
    featInfo: [],
    description: 'ImperialGriffon',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [
      {
        token: 'fly',
      }],
    attachments: [],
    img: ImperialGriffon,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  TemplarChampion: {
    name: 'Templar Champion',
    type: 'warrior',
    subtype: 'fighter',
    power: 3,
    currentP: 3,
    defPower: 2,
    currentDP: 2,
    health: 7,
    currentHP: 7,
    cost: 5,
    currentC: 5,
    justDeployed: true,
    featInfo: ['PIERCING'],
    description: 'TemplarChampion',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [{
      name: 'invoke',
      aim: ['warrior'],
      type: 'good',
      value: {
        img: TemplarChampion,
        name: 'fake',
        type: 'spell',
        subtype: 'instant',
        currentC: 0,
        featInfo: [],
        description: 'TemplarChampCast',
        faction: 'Castle',
        place: '',
        features: [{
          attach: false, aim: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'good', name: 'heal', value: 3, aimStatus: 'field',
        }],
        status: 'hand',
      },
      condition: 'onplay',
    },
    {
      name: 'attack', condition: 'onattack', type: 'bad', aim: ['otherWarInRow', 'warrior', 'flyer', 'shooter', 'fighter'], value: 2, apply: 'attacked', status: 'field', school: 'light',
    }],
    attachments: [],
    img: TemplarChampion,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  MasterOfLight: {
    name: 'Master Of Light',
    type: 'warrior',
    subtype: 'fighter',
    power: 5,
    currentP: 5,
    defPower: 4,
    currentDP: 4,
    health: 9,
    currentHP: 9,
    cost: 7,
    currentC: 7,
    justDeployed: true,
    featInfo: [],
    description: 'MasterOfLight',
    faction: 'Castle',
    id: _.uniqueId(),
    features: [{
      attach: false, type: 'bad', aim: ['row', 'warrior', 'flyer', 'shooter', 'fighter'], value: 3, name: 'attack', condition: 'insteadatk', cost: 0, aimStatus: 'field', description: 'lightAttack', school: 'light',
    }],
    attachments: [],
    img: MasterOfLight,
    status: 'hand',
    turn: 1,
    disabled: false,
  },
  YouthFountain: {
    name: 'Youth Fountain',
    type: 'spell',
    subtype: 'temporary',
    cost: 2,
    currentC: 2,
    featInfo: ['TEMPORARY'],
    description: 'YouthFountain',
    faction: 'Castle',
    id: _.uniqueId(),
    place: 'bigSpell',
    features: [{
      spell: true, attach: ['field', 'warrior'], type: 'bad', name: 'ownerHeroHeal', aim: ['warrior', 'flyer', 'shooter', 'fighter'], condition: 'onplay', value: 2, aimStatus: 'field',
    },
    {
      spell: true, attach: ['field', 'warrior'], type: 'bad', name: 'ownerHeroHeal', aim: ['warrior', 'flyer', 'shooter', 'fighter'], condition: 'onmove', value: 2, aimStatus: 'field',
    }],
    img: YouthFountain,
    status: 'hand',
    disabled: false,
  },
  RetaliationHammer: {
    name: 'Retaliation Hammer',
    type: 'spell',
    subtype: 'instant',
    cost: 2,
    currentC: 2,
    featInfo: ['INSTANT'],
    description: 'RetaliationHammer',
    faction: 'Castle',
    id: _.uniqueId(),
    place: '',
    heroSpell: false,
    features: [
      {
        spell: true, attach: false, type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'attack', value: 2, aimStatus: 'field', school: 'light',
      },
      {
        spell: true, attach: ['warrior'], type: 'bad', aim: ['warrior', 'flyer', 'shooter', 'fighter'], name: 'moveAdjasent', charges: 1, immediate: true, aimStatus: 'field',
      },
    ],
    img: RetaliationHammer,
    status: 'hand',
    disabled: false,
  },
  RetributionSword: {
    name: 'Retribution Sword',
    type: 'spell',
    subtype: 'permanent',
    cost: 3,
    currentC: 3,
    description: 'RetributionSword',
    faction: 'Castle',
    id: _.uniqueId(),
    place: 'warrior',
    showCharges: true,
    featInfo: ['ARTEFACT'],
    charges: 2,
    curCharges: 2,
    features: [
      {
        spell: true,
        attach: ['hero'],
        aim: ['hero'],
        type: 'good',
        name: 'invoke',
        description: 'retributionSword',
        aimStatus: 'field',
        condition: 'insteadatk',
        charges: 2,
        cost: 0,
        value: {
          img: RetributionSword,
          name: 'fake',
          type: 'spell',
          subtype: 'instant',
          currentC: 0,
          description: 'AddAttackCast',
          faction: 'Castle',
          place: '',
          featInfo: [],
          features: [{
            spell: true,
            attach: ['warrior', 'flyer', 'shooter', 'fighter'],
            aim: ['warrior', 'fighter', 'shooter', 'flyer'],
            type: 'good',
            name: 'atkPower',
            value: 1,
            depend: 'adjasentAlly',
            dependValue: 1,
            charges: 1,
            aimStatus: 'field',
          }],
          status: 'hand',
        },
      }],
    img: RetributionSword,
    status: 'hand',
    disabled: false,
  },
  Morale: {
    name: 'Dummy',
    type: 'spell',
    subtype: 'instant',
    featInfo: ['INSTANT'],
    description: 'Morale',
    cost: 0,
    currentC: 0,
    faction: 'Castle',
    id: '',
    attachments: [],
    features: [{
      attach: false, type: 'good', aim: ['warrior'], name: 'increasePoints', value: 1, condition: 'insteadatk', cost: 0, description: 'increasePoints',
    },
    {
      attach: false, type: 'all', aim: ['warrior'], name: 'drawCard', condition: 'insteadatk', cost: 0, description: 'drawCard',
    }],
    img: GoodMorale,
    status: 'hand',
    player: 'player2',
    turn: 0,
  },
  TemplarChampCast: {
    img: TemplarChampion,
    name: 'fake',
    type: 'spell',
    subtype: 'instant',
    currentC: 0,
    featInfo: [],
    description: 'TemplarChampCast',
    faction: 'Castle',
    place: '',
    features: [{
      attach: false, aim: ['warrior', 'flyer', 'shooter', 'fighter'], type: 'good', name: 'heal', value: 3, aimStatus: 'field',
    }],
    status: 'hand',
  },
  AddAttackCast: {
    img: RetributionSword,
    name: 'fake',
    type: 'spell',
    subtype: 'instant',
    currentC: 0,
    description: 'AddAttackCast',
    faction: 'Castle',
    place: '',
    featInfo: [],
    features: [{
      spell: true,
      attach: ['warrior', 'flyer', 'shooter', 'fighter'],
      aim: ['warrior', 'fighter', 'shooter', 'flyer'],
      type: 'good',
      name: 'power',
      value: 1,
      depend: 'adjasentAlly',
      dependValue: 1,
      charges: 1,
      aimStatus: 'field',
    }],
    status: 'hand',
  },
  BannermanCast: {
    img: BannerMan,
    name: 'fake',
    type: 'spell',
    subtype: 'instant',
    currentC: 0,
    featInfo: [],
    description: 'BannermanCast',
    faction: 'Castle',
    place: '',
    features: [{
      attach: ['warrior'], aim: ['warrior', 'fighter', 'shooter', 'flyer'], type: 'good', name: 'power', value: 2, charges: 1, id: _.uniqueId(), aimStatus: 'field',
    }],
    status: 'hand',
  },
};

export default castleDeck;

// depend: 'goodAttachments',
